### ISSUE TITLE
Teradici PCoIP WDDM driver not supported

### ISSUE THREAD

**Issue by mimosa2** [constellation-app/constellation#101]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Tested on Amazon workspace without GPU support and it failed with error below;
```
com.jogamp.opengl.GLException: Profile GL3 is not available on null, but: [GLProfile[GL2ES1/GL2.sw], GLProfile[GL2ES2/GL2.sw], GLProfile[GL2/GL2.sw], GLProfile[GL2/GL2.sw], GLProfile[GL2GL3/GL2.sw]]
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1004)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.SharedDrawable.getGLProfile(SharedDrawable.java:143)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.SharedDrawable.getGLCapabilities(SharedDrawable.java:159)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLVisualProcessor.<init>(GLVisualProcessor.java:394)
	at au.gov.asd.tac.constellation.graph.interaction.visual.InteractiveGLVisualProcessor.<init>(InteractiveGLVisualProcessor.java:89)
	at au.gov.asd.tac.constellation.graph.interaction.visual.GLInteractiveVisualManagerFactory.constructVisualManager(GLInteractiveVisualManagerFactory.java:49)
	at au.gov.asd.tac.constellation.functionality.visual.VisualGraphTopComponent.<init>(VisualGraphTopComponent.java:429)
	at au.gov.asd.tac.constellation.functionality.visual.VisualGraphOpener$GraphFileOpener.done(VisualGraphOpener.java:225)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to Reproduce

1. Download Constellation 
2. Select File -> New graph

**Expected behaviour:** 
This vm doesn't have the supported GPU so the above error is expected. This for your information only.
**Actual behaviour:** 
Unsupported graphics card error message appeared. 
**Reproduces how often:** 
100%

**Comment by mimosa2** [comment]
[messages.log](https://github.com/constellation-app/constellation/files/3518673/messages.log)

**Comment by antares1470** [comment]
This was to document the issue of not working without graphics cards. This issue should hopefully be dealt with in the work done here: https://github.com/constellation-app/constellation-web
