### ISSUE TITLE
Testing for Release v2.3

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#1046]
# Testing Constellation for v2.3 Release

This testing suite was generated using https://github.com/constellation-app/miscellaneous/blob/master/TestCaseGenerator/generate_test_cases.py

### Testing Conversation View 

* [x] In progress

1. Click on Views > Conversation View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Conversation View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Conversation View 

### Testing Data Access View 

* [x] In progress

1. Click on Views > Data Access View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Data Access View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Data Access View 

### Testing Histogram View 

* [x] In progress

1. Click on Views > Histogram View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Histogram View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Histogram View 

### Testing Layers View 

* [x] In progress

1. Click on Views > Layers View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Layers View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Layers View 

### Testing Notes View 

* [x] In progress

1. Click on Views > Notes View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Notes View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Notes View 

### Testing Plugin Reporter View 

* [x] In progress

1. Click on Views > Plugin Reporter View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Plugin Reporter View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Plugin Reporter View 

### Testing Quality Control View 

* [x] In progress

1. Click on Views > Quality Control View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Quality Control View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Quality Control View 

### Testing Table View 

* [x] In progress

1. Click on Views > Table View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Table View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Table View 

### Testing Timeline View 

* [x] In progress

1. Click on Views > Timeline View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Timeline View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Timeline View 

### Testing Welcome View 

* [x] In progress

1. Click on Views > Welcome View 
1. Are there any errors or exceptions thrown?
1. If the view is enabled, can you click on any buttons (if applicable)?
1. Did each button work as intended?
1. Are there any exceptions or errors thrown?
1. If the view is enabled, can you click on any drop down lists (if applicable)?
1. Did each drop down list work as intended?
1. Are there any exceptions or errors thrown?
1. Close the View
1. Click on File > New Graph
1. Open the Welcome View  again
1. Are there any errors or exceptions thrown?
1. Is the view still disabled? If so this is likely a problem!
1. Click the buttons
1. Did each button work as intended?
1. Are there any errors or exceptions thrown?
1. Click on drop down lists
1. Did each drop down list work as intended?
1. Are there any errors or exceptions thrown?

* [x] Completed testing the Welcome View 

### Testing Display > Add Blazes (AddBlazeAction.java)

* [x] In progress

1. Try to click on Display > Add Blazes
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Display > Add Blazes
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Display > Add Blazes

### Testing Display > Add Custom Blazes (AddCustomBlazeAction.java)

* [x] In progress

1. Try to click on Display > Add Custom Blazes
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Display > Add Custom Blazes
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Display > Add Custom Blazes

### Testing Experimental/Developer > Test Autosave (AutosaveTestAction.java)

* [x] In progress

1. Try to click on Experimental/Developer > Test Autosave
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Experimental/Developer > Test Autosave
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Experimental/Developer > Test Autosave

### Testing Tools > Complete with Schema (CompleteSchemaAction.java)

* [x] In progress

1. Try to click on Tools > Complete with Schema
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Tools > Complete with Schema
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Tools > Complete with Schema

### Testing  (CopyToClipboardAction.java)

* [x] In progress

1. Try to click on 
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on 
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing 

### Testing Edit > Copy to New Graph (CopyToNewGraphAction.java)

* [x] In progress

1. Try to click on Edit > Copy to New Graph
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Edit > Copy to New Graph
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Edit > Copy to New Graph

### Testing Cosine Similarity (CosineSimilarityAction.java)

* [x] In progress

1. Try to click on Cosine Similarity
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Cosine Similarity
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Cosine Similarity

### Testing  (CutToClipboardAction.java)

* [x] In progress

1. Try to click on 
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on 
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing 

### Testing Selection >  (DeSelectBlazesAction.java)

* [x] In progress

1. Try to click on Selection > 
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Selection > 
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Selection > 

### Testing Edit > Delete (DeleteSelectionAction.java)

* [x] In progress

1. Try to click on Edit > Delete
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Edit > Delete
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Edit > Delete

### Testing Selection > Deselect All (DeselectAllAction.java)

* [x] In progress

1. Try to click on Selection > Deselect All
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Selection > Deselect All
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Selection > Deselect All

### Testing Selection > Deselect Transactions (DeselectTransactionsAction.java)

* [x] In progress

1. Try to click on Selection > Deselect Transactions
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Selection > Deselect Transactions
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Selection > Deselect Transactions

### Testing Selection > Deselect Nodes (DeselectVerticesAction.java)

* [x] In progress

1. Try to click on Selection > Deselect Nodes
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Selection > Deselect Nodes
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Selection > Deselect Nodes

### Testing File/Import > From JDBC Source... (ImportJDBCFileAction.java)

* [x] In progress

1. Try to click on File/Import > From JDBC Source...
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on File/Import > From JDBC Source...
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing File/Import > From JDBC Source...

### Testing Pagerank Centrality (PagerankCentralityAction.java)

* [x] In progress

1. Try to click on Pagerank Centrality
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Pagerank Centrality
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Pagerank Centrality

### Testing  (PasteFromClipboardAction.java)

* [x] In progress

1. Try to click on 
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on 
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing 

### Testing File >  (RecentFileAction.java)

* [x] In progress

1. Try to click on File > 
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on File > 
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing File > 

### Testing Experimental/Build Graph > Small World Graph Builder (SmallWorldGraphBuilderAction.java)

* [x] In progress

1. Try to click on Experimental/Build Graph > Small World Graph Builder
1. If the menu is disabled this may be as per design, can you confirm this?
1. Click on File > New Graph
1. Click on Experimental/Build Graph > Small World Graph Builder
1. Did the menu work as intended?
1. Are there any exceptions?

* [x] Completed testing Experimental/Build Graph > Small World Graph Builder

**Comment by arcturus2** [comment]
**Issue 1**

One issue is with the Open Street Map not working. Other maps work ok.

```
INFO [null]: Last record repeated again.
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at processing.core.PApplet.loadBytes(PApplet.java:7313)
	... 4 more
java.io.IOException: Server returned HTTP response code: 403 for URL: https://tile.openstreetmap.org/5/30/19.png
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor92.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
```

The link works browsing normally to https://tile.openstreetmap.org/5/30/19.png but not via Constellation for some reason.

**Comment by arcturus2** [comment]
**Issue 2**

The GDELT import plugins are not working because it is unable to download a file its looking for. It looks like the format of the file is looking for todays date but on the server it is a couple of days behind so I think the plugin can be modified to use the file 2 days ago. I can PR that int to fix it.

```
java.io.FileNotFoundException: http://data.gdeltproject.org/gkg/20210528.gkg.csv.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at au.gov.asd.tac.constellation.views.dataaccess.adaptors.plugins.utilities.GDELTImportingUtilities.retrieveEntities(GDELTImportingUtilities.java:48)
[catch] at au.gov.asd.tac.constellation.views.dataaccess.adaptors.plugins.importing.ImportEntitiesFromGDELTPlugin.query(ImportEntitiesFromGDELTPlugin.java:121)
	at au.gov.asd.tac.constellation.views.dataaccess.templates.RecordStoreQueryPlugin.lambda$query$0(RecordStoreQueryPlugin.java:139)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
