### ISSUE TITLE
3d Scattergram for main graph

### ISSUE THREAD

**Issue by spjspj** [constellation-app/constellation#118]
Would be nice to be able to have a 3d scattergram with x,y,z axis and grid lines shown explicitly on the graph (so can still turn it around so forth).  Maybe limited to having X,Y,Z directions as numbers only.

Be able to extend this by animating it in 4D (with a X,Y,Z coordinate function based on the time field) - I was thinking maybe being able to do a planetarium display (with the sun in it to size and then then moon orbiting the earth and then all 8 planets orbitting in the correct ellipse and orbit and the correct tilt for the earth or similar).

**Comment by cygnus-x-1** [comment]
I find 3d scatter charts are inherently difficult to interpret, as they can have points hidden behind other points, and other optical illusions. This can be worked around somewhat by making the chart interactive, but an interactive 3d scatter chart is no simple thing to create. You could probably also get most of the way there simply by laying the graph out based on attribute values.

**Comment by spjspj** [comment]
@cygnus-x-1 Yeah, I believe it would only work with numerical values for at least 2 of the 3 dimensions (maybe enforcing all 3 to be numerical).  Similar to how the sphere plot does stuff now.  I think maybe axes would be hardish to do as well?  Not sure.

**Comment by CrucisGamma** [comment]
Please don't delete this!

**Comment by CrucisGamma** [comment]
Am currently working on this.  Basically figuring out how to get the actual value to be added into the graph that's passed into a copy of GridArranger (copied and renamed into Scatter3DArranger).  I'm basically only getting X,Y,Z,X2,Y2 and Z2.  I've done a:
```
final int rawAttr = AnalyticConcept.VertexAttribute.RAW.ensure(wg);
```
but am getting null when I do a:
```
                wg.getFloatValue(xAttr, vxId);
                String raw = wg.getStringValue(rawAttr, vxId);  
                ^^ null in raw.
```
The call stack for it to get to this point is:
```
	at au.gov.asd.tac.constellation.plugins.arrangements.scatter3d.Scatter3dArranger.arrange(Scatter3dArranger.java:118)
	at au.gov.asd.tac.constellation.plugins.arrangements.scatter3d.ArrangeInScatter3dGeneralPlugin.edit(ArrangeInScatter3dGeneralPlugin.java:76)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.describedEdit(SimpleEditPlugin.java:204)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:112)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.executePluginNow(DefaultPluginEnvironment.java:209)
	at au.gov.asd.tac.constellation.plugins.PluginExecutor$PluginEntry.executeNow(PluginExecutor.java:406)
	at au.gov.asd.tac.constellation.plugins.PluginExecutor$1.execute(PluginExecutor.java:256)
	at au.gov.asd.tac.constellation.plugins.templates.SimplePlugin.run(SimplePlugin.java:65)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:123)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment$$Lambda$886.615736511.call
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```

**Comment by arcturus2** [comment]
Hi @CrucisGamma so just to elaborate on the `AnalyticConcept.VertexAttribute.RAW` attribute, it is typically used to store the original value should the schema then change it based on the schema rules and update the `VisualConcept.VertexAttribute.IDENTIFIER` and `AnalyticConcept.VertexAttribute.TYPE` attributes.

For example see https://github.com/constellation-app/constellation/blob/958c0bde23df4cae37cc56e553a57e58db4ed9f4/CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/AnalyticSchemaFactory.java#L155

So depending on how you are importing your sample dataset, `AnalyticConcept.VertexAttribute.RAW` could be `null`.

**Comment by spjspj** [comment]
Hi @arcturus2  

The graph I was working with definitely had RAW setup for it but it wasn't coming through from the stock standard inclusiongraph that I was using (it only has nRadius, X, X2, Y, Y2, Z, Z2).

I also found the following yesterday which I believe will let me get the data I need.
>>> in here (AbstractInclusionGraph): incNradiusAttr 
```
    public void addAttributeToCopy(final Attribute attr) {
```

I might put in a ticket that asks for a a way to iterate over attributes that have had non-default data in them
