### ISSUE TITLE
Effective Resistance Exception

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1296]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

An IllegalArgumentException is thrown if you try to run the Effective Resistance analytic on an empty graph:
```
java.lang.IllegalArgumentException: Rows of src can't be zero
	at org.ejml.ops.DConvertArrays.convert(DConvertArrays.java:35)
	at org.ejml.data.DMatrixRMaj.set(DMatrixRMaj.java:397)
	at org.ejml.data.DMatrixRMaj.<init>(DMatrixRMaj.java:98)
	at org.ejml.simple.SimpleMatrix.<init>(SimpleMatrix.java:136)
	at au.gov.asd.tac.constellation.plugins.algorithms.MatrixUtilities.adjacency(MatrixUtilities.java:48)
	at au.gov.asd.tac.constellation.plugins.algorithms.MatrixUtilities.laplacian(MatrixUtilities.java:81)
	at au.gov.asd.tac.constellation.plugins.algorithms.MatrixUtilities.inverseLaplacian(MatrixUtilities.java:87)
	at au.gov.asd.tac.constellation.plugins.algorithms.sna.metrics.EffectiveResistancePlugin.edit(EffectiveResistancePlugin.java:74)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:173)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.executeEditPluginNow(DefaultPluginEnvironment.java:282)
	at au.gov.asd.tac.constellation.plugins.PluginExecution.executeNow(PluginExecution.java:331)
[catch] at au.gov.asd.tac.constellation.views.analyticview.analytics.ScoreAnalyticPlugin.edit(ScoreAnalyticPlugin.java:205)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.describedEdit(SimpleEditPlugin.java:207)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:115)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:129)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to Reproduce

1. Open an new empty graph
2. Open Analytic View
3. Select the Effective Resistance Analytic
4. Run the analytic

**Expected behaviour:** Analytic either shouldn't run or should generate no results (similar to other analytics)

**Actual behaviour:** Exception

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by Auriga2** [comment]
Looks good in constellation-win-master-2021-11-09 build.
