### ISSUE TITLE
Runtime exception when the notes view is open

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1313]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I have observed the below runtime error for JavaFX  pop up a few times when I have the notes view open and I am working on a few different graphs. I can't reproduce it from any exact steps so not sure what the sequence of events is to trigger it. On some of my graphs I have been filtering on the auto filters so that might have something to do with it. 

### Steps to Reproduce

1.  Open up a couple of views including the Notes View
2.  Check the auto filters on a couple of the graph and navigate to another graph that doesn't have any notes
3.  Continue working on the graphs > observe runtime error (no exact steps)

**Expected behaviour:** there is no runtime error for my graphs

**Actual behaviour:** runtime error observed

**Reproduces how often:** Random. 

### Additional Information
![image](https://user-images.githubusercontent.com/83679004/131078301-64c90919-3fcc-41c8-a09a-7bec7ccbfca6.png)

Here is a copy of what I had open at the time: 
![image](https://user-images.githubusercontent.com/83679004/131078353-4447526d-afa1-4f17-9082-77d8458abdb0.png)

```java
java.lang.IllegalStateException: Not on FX application thread; currentThread = Default Plugin Environment
	at javafx.graphics/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$3.onProposedChange(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.updateChildren(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.lambda$new$11(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
[catch] at javafx.base/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at javafx.controls/javafx.scene.control.Labeled.setText(Unknown Source)
	at impl.org.controlsfx.skin.CheckComboBoxSkin$2.updateItem(CheckComboBoxSkin.java:133)
	at javafx.controls/javafx.scene.control.ListCell.updateItem(Unknown Source)
	at javafx.controls/javafx.scene.control.ListCell.lambda$new$2(Unknown Source)
	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at javafx.base/javafx.collections.ModifiableObservableListBase.addAll(Unknown Source)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.updateTagsFiltersAvailable(NotesViewPane.java:968)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.addPluginReport(NotesViewPane.java:389)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$setGraphReport$6(NotesViewPane.java:354)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.setGraphReport(NotesViewPane.java:351)
	at au.gov.asd.tac.constellation.views.notes.NotesViewTopComponent.newPluginReport(NotesViewTopComponent.java:149)
	at au.gov.asd.tac.constellation.plugins.reporting.GraphReportManager.lambda$fireNewPluginReport$0(GraphReportManager.java:72)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.plugins.reporting.GraphReportManager.fireNewPluginReport(GraphReportManager.java:72)
	at au.gov.asd.tac.constellation.plugins.reporting.GraphReport.addPluginReport(GraphReport.java:90)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:94)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by GammaVel** [comment]
Looking good with Release 2.4, I am not seeing the runtime error anymore. I'll keep an eye on it as it was showing up randomly for me before and if it happens again I will raise a new issue for it. Happy to close this one off. Thanks Constellation team!
