### ISSUE TITLE
Notes View Concurrent Mod

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#1342]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1542)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$setNotes$8(NotesViewPane.java:432)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

In a highly connected graph if I continue hopping out I am able to sometimes produce this error with the notes view open.

**Expected behaviour:** \[What you expect to happen\]
No Errors

**Actual behaviour:** \[What actually happens\]
Concurrent Mod Error

**Reproduces how often:** \[What percentage of the time does it reproduce?\]
40%

### Additional Information

Any additional information, configuration or data that might be
necessary to reproduce the issue.

**Comment by GammaVel** [comment]
I'm not seeing this with Release 2.4, it is looking good. Thank you @arcturus2 :-)
