### ISSUE TITLE
Support for a generic JDBC connector

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#141]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The ability to connect Constellation to a database using JDBC is required for end users to be able to import data into Constellation without needing to be a developer and writing their own connector.

The JDBC Import GUI should allow a user to connect to a database by providing the host, port, database, username and password.

You should be able type your SQL query and then map the results to node or transaction attributes.

Consider using the Import From Delimited to implement the GUI.

The intention would be that a generic connector should work with MySQL, Postgres, Impala, Phoenix and for Hive's using their JDBC driver.

Ideally Kerberos support would be good to have but for the initial version maybe keep it out of scope.

Suggestions welcomed.

**Comment by arcturus2** [comment]
A basic experimental version is available but I'd like to look at doing a new one in JavaFX and probably link it in with the delimited file importer. Following on from the developer catchup I said I would close this and create a new one...going to back track on that and instead put this ticket back in todo which should cover the final solution.

**Comment by cygnus-x-1** [comment]
Since the Delimited File Importer is now a sidebar thing - could we also make this a sidebar thing for consistency?

**Comment by aldebaran30701** [comment]
@cygnus-x-1 I've made a ticket just now upon seeing your comment - #956

**Comment by cygnus-x-1** [comment]
I ran into some major issues, but first here are some usability comments:

- The workflow is add a driver > add a connection using that driver > query a database using that connection, however the UI asks you to set this up in the reverse order.
- When adding a driver, the file dialog should limit to only relevant file types (JAR presumably).
- You currently cannot add a connection without entering a username / password, even if it is not required.
- I'm unclear why there is an option for a username and password as that information was requested as part of the connection setup. Perhaps it was only needed for testing the connection there? If that's the case, then the UI should indicate that.
- There is no way to modify a driver or connection once it has been created short of removing and re-adding it.
- The instructions in the 'Configuration' pane don't actually mention that you need to perform an SQL query to retrieve sample data before dragging and dropping attributes.
- I am unable to perform metadata queries of a database (.table, .schema <my-table>, etc) as they fail validation.
- The content is enough such that it is put into scrollable pane, which cuts off the 'Cancel' and 'Import' buttons. Perhaps a more compact layout would be beneficial?

The major issues started when I attempted to perform valid SQL queries against my test database. For reference, [here's the database](https://github.com/lerocha/chinook-database) I was using to test, and I was using the SQLite version (alongside the [SQLite JDBC driver](https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc)). With this setup, I was unable to get any result back, but would instead receive the following on a "successful" query...

`java.lang.IllegalStateException: SQLite JDBC: inconsistent internal state
	at org.sqlite.core.CoreResultSet.checkCol(CoreResultSet.java:88)
	at org.sqlite.jdbc3.JDBC3ResultSet.getColumnCount(JDBC3ResultSet.java:703)
	at au.gov.asd.tac.constellation.plugins.importexport.jdbc.ImportController.updateSampleData(ImportController.java:438)
	at au.gov.asd.tac.constellation.plugins.importexport.jdbc.SourcePane.lambda$new$11(SourcePane.java:495)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8889)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
[catch] at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

Google tells me this can occur when you get back zero records and are not handling the cursor correctly, but there should have been more than zero records returned (I verified this in NetBeans). All I can think of is that the query is failing because it's using a username and password which are not actually required.

I'm sure I'll have more feedback once I can access my data, but this should be enough for now.

**Comment by antares1470** [comment]
I've created tickets #987 and #988 which outline the stuff @cygnus-x-1 found above. Consequently closing this ticket
