### ISSUE TITLE
Runtime error with Cluster > K-truss when there are no K-trusses on graph and clicking on "V"

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1460]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation is throwing a runtime error on the K-Truss screen if there are no K-trusses on the graph and the user selects the "V" button (If there are K-trusses in that section it would show them as a line graph). The run time error is happening with a new graph with only a couple of nodes, or a larger graph that has more nodes but doesn't have any triangular relationships. 
The following run time error is shown: 

java.lang.ArithmeticException: / by zero
	at au.gov.asd.tac.constellation.plugins.algorithms.clustering.ktruss.NestedKTrussDisplayPanel.rectY(NestedKTrussDisplayPanel.java:126)
	at au.gov.asd.tac.constellation.plugins.algorithms.clustering.ktruss.NestedKTrussDisplayPanel.paintComponent(NestedKTrussDisplayPanel.java:93)

### Steps to Reproduce

1.  Open a new graph and connect a couple of nodes
2.  Go to Tools > Cluster > Ktruss
3.  Click on Cluster
4. Click on Toggle Interactive Disabled
5.  Click on the "V" button which is top left of the screen > run time error
6. To get rid of this runtime error you will need to close and reopen Constellation
7.  Repeat with another graph that doesn't have the triangular relationships > same run time error

**Expected behaviour:** The runtime error is caught before it is shown to me

**Actual behaviour:** Run time error as per the test steps
**Reproduces how often:** 100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/135386173-492ee07d-0959-4fde-a6cf-2dcda97ac59f.png)
![image](https://user-images.githubusercontent.com/83679004/135386616-74f76855-baf8-40fe-9e02-7372e856e1c9.png)

**Comment by GammaVel** [comment]
hi @aldebaran30701. Thank you for fixing my issue and I noticed it didn't take you very long to resolve. I have confirmed this error is no longer being displayed. Brilliant!
