### ISSUE TITLE
Resolve compatability between v2.4 and anticipated v2.5

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#1476]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Major refactoring of code is currently underway in PR's (https://github.com/constellation-app/constellation/pull/1415) and another already in `master` being the Table View refactor. Though these changes are necessary, we should look to make sure the migration from versions prior to the anticipated v2.5 work seemlessly with v2.5.

There is an issue identified with the Data Access View that will occur when #1415 is merged in because the Top Component has moved packages. The state of the views make reference to the full class path including the package name so for instance if you have the Data Access View open in v2.4 and move to v2.5, there is an exception that is thrown (because the class was not found) and the view opens in the graphs section rather than on the left pane. This is a result of the exception.

A similar issue is likely with the Table View as it's Top Component has moved packages.

One option is to temporarily restore these packages to their old package until v3's release next year.

### Steps to Reproduce

1. Open the Data Access View in v2.4
2. Close v2.4
3. Open v2.5

**Expected behaviour:** \[What you expect to happen\]
The Data Access View stays open in the position when it was closed in v2.4

**Actual behaviour:** \[What actually happens\]
The Data Access View opens in the "explorer" graph position

**Reproduces how often:** \[What percentage of the time does it reproduce?\]
100%

### Additional Information

All views should be opened in v2.4 and then in v2.5 and made sure they look and operate as expected.

Note that if v2.5 is not build then compile a stand alone version from the branch or `master`.

**Comment by arcturus2** [comment]
So I tried adding something to `OnStart` to replace the `config/Windows2Local/Components/DataAccessViewTopComponent.settings` file with the new package name but it still did not work because there must be something in the serial data that is retaining this information.

I tried:

```java
@OnStart
public class OnLoading implements Runnable {

    private static final Logger LOGGER = Logger.getLogger(OnLoading.class.getName());

    @Override
    public void run() {
        final File userDirectory = Places.getUserDirectory();
        if (userDirectory != null) {
            File file = new File(userDirectory.getAbsoluteFile() + File.separator + "/config/Windows2Local/Components/DataAccessViewTopComponent.settings");
            if (file.exists()) {
                try (final InputStream input = new FileInputStream(file)) {
                    String content = IOUtils.toString(input, StandardCharsets.UTF_8.name());
                    content = content.replaceAll("au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent", "au.gov.asd.tac.constellation.views.dataaccess.DataAccessViewTopComponent");
                    try (final FileOutputStream output = new FileOutputStream(file)) {
                        IOUtils.write(content, output, StandardCharsets.UTF_8.name());
                    }
                } catch (FileNotFoundException ex) {
                    Exceptions.printStackTrace(ex);
                } catch (IOException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        }
    }

}
```

And I was able to check with a before....

```bash
$ find . -type f | xargs grep DataAccessViewTopComponent --color
./Preferences/org/netbeans/core/windows/tctracker.properties:DataAccessViewTopComponent=true
./Windows2Local/Modes/.nbattrs:        <attr name="WinSys-TCRef-Order" stringvalue="favorites/PerspectiveBookmarkTopComponent/ScatterPlotTopComponent/AnalyticViewTopComponent/NamedSelectionTopComponent/HistogramTopComponent/LayersViewTopComponent/PlaneManagerTopComponent/DelimitedImportTopComponent/QualityControlViewTopComponent/AttributeEditorTopComponent/NotesViewTopComponent/SchemaViewTopComponent/MapViewTopComponent/JDBCImportTopComponent/DataAccessViewTopComponent/ScriptingViewTopComponent/ConversationViewTopComponent"/>
./Windows2Local/Modes/explorer/DataAccessViewTopComponent.wstcref:    <tc-id id="DataAccessViewTopComponent" />
./Windows2Local/Modes/explorer.wsmode:    <active-tc  id="DataAccessViewTopComponent" />
./Windows2Local/Components/DataAccessViewTopComponent.settings:    <instanceof class="au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent"/>
./Windows2Local/Components/DataAccessViewTopComponent.settings:    <serialdata class="au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent">
./Windows2Local/WindowManager.wswmgr:  <tc-id id="DataAccessViewTopComponent"/>
```

and after ...

```bash
$ find . -type f | xargs grep DataAccessViewTopComponent --color
./Preferences/org/netbeans/core/windows/tctracker.properties:DataAccessViewTopComponent=true
./Windows2Local/Components/DataAccessViewTopComponent.settings:    <instanceof class="au.gov.asd.tac.constellation.views.dataaccess.DataAccessViewTopComponent"/>
./Windows2Local/Components/DataAccessViewTopComponent.settings:    <serialdata class="au.gov.asd.tac.constellation.views.dataaccess.DataAccessViewTopComponent">
```

But I still get the exception...

```
INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'DataAccessViewTopComponent'. Reason: java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent starting from SystemClassLoader[115 modules] with possible defining loaders [ModuleCL@7aa8af15[au.gov.asd.tac.constellation.views.dataaccess]] and declared parents [org.netbeans.MainImpl$BootClassLoader@61a485d2, org.netbeans.JarClassLoader@59b1efd7, ModuleCL@ca579e1[org.netbeans.api.annotations.common], ModuleCL@4faefee2[org.openide.awt], ModuleCL@2c4ffe15[org.netbeans.api.progress], ModuleCL@7280bbbf[org.netbeans.api.progress.nb], ModuleCL@554dae7f[org.openide.dialogs], ModuleCL@6d2c03da[org.openide.nodes], ModuleCL@3ec0f73c[org.openide.windows], ModuleCL@49eafe18[org.netbeans.libs.batik.read], ...98 more]
java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent starting from SystemClassLoader[115 modules] with possible defining loaders [ModuleCL@7aa8af15[au.gov.asd.tac.constellation.views.dataaccess]] and declared parents [org.netbeans.MainImpl$BootClassLoader@61a485d2, org.netbeans.JarClassLoader@59b1efd7, ModuleCL@ca579e1[org.netbeans.api.annotations.common], ModuleCL@4faefee2[org.openide.awt], ModuleCL@2c4ffe15[org.netbeans.api.progress], ModuleCL@7280bbbf[org.netbeans.api.progress.nb], ModuleCL@554dae7f[org.openide.dialogs], ModuleCL@6d2c03da[org.openide.nodes], ModuleCL@3ec0f73c[org.openide.windows], ModuleCL@49eafe18[org.netbeans.libs.batik.read], ...98 more]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:769)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.openide.windows.TopComponent$Replacer.readObject(TopComponent.java:1821)
Caused: java.io.IOException
	at org.openide.windows.TopComponent$Replacer.readObject(TopComponent.java:1881)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2273)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.readSerial(XMLSettingsSupport.java:546)
	at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.instanceCreate(XMLSettingsSupport.java:578)
	at org.netbeans.modules.settings.convertors.SerialDataConvertor$SettingsInstance.instanceCreate(SerialDataConvertor.java:401)
[catch] at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:547)
	at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:657)
	at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
	at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:1002)
	at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:270)
	at org.openide.windows.OpenComponentAction.getTopComponent(OpenComponentAction.java:53)
	at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:66)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:174)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:70)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:91)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:74)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:177)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6396)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5007)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by arcturus2** [comment]
Resetting the cache is a way to resolve this and a script has been made available in the root level when you unzip the zip file. See https://github.com/constellation-app/constellation-applications/pull/3 for more details.

**Comment by GammaVel** [comment]
This is an interesting issue @antares1470 and @arcturus2. I have used the reset.bat and it was quite handy so that is very useful to have for new releases. I liked the warning it gave too. It would be great to promote it more broadly, noting it was on the latest blog. FAQs might be good on the main Constellation website, something to consider
