### ISSUE TITLE
Notes View Null Pointer Exception

### ISSUE THREAD

**Issue by Constellation-Developer** [constellation-app/constellation#1528]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Linux OS.
Current Master.
Running via NetBeans.
When working on the graph with Notes View opened, an exception occurs.
```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.createNote(NotesViewPane.java:622)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$updateNotesUI$13(NotesViewPane.java:517)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$updateNotesUI$14(NotesViewPane.java:516)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

### Steps to Reproduce

1. Open Constellation
2. Open New Graph
3. Add a few vertices
4. Enable the Notes View filter to show all note types
5. Create one user note
6. Use select in box to make some auto notes
7. Experimental -> build graph -> sphere graph builder

**Expected behaviour:** \[What you expect to happen\]
No exception to occur
**Actual behaviour:** \[What actually happens\]
Exception occurs.
**Reproduces how often:** \[What percentage of the time does it reproduce?\]
20%
### Additional Information
The opening of the Sphere Graph Builder Pane may not be a prerequisite of this issue being replicated as it seems to stem from the "createNotes()" method which appears to be updating the notes when a new plugin report occurs.

**Comment by HolandCrick** [comment]
@antares1470  Thank you for fixing the bug, the "Notes View Null Pointer Exception" replication is difficult as it comes intermittently. Look like the issue is resolved and new code working nicely..
