### ISSUE TITLE
Rename Step Tabs in Data Access View

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1599]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Would be handy to be able to rename the step tabs in the Data Access View. This would allow you to then make clearer what each step is aiming to do. This could also then be saved and loaded as part of the templates.

### Behaviour

* Try to include measurable metrics that can be aimed for (if applicable to the issue),
e.g. if it's a time issue then "should take 5 seconds or less to finish"
or if it's a workflow issue "should be accomplished in 2 or less clicks".

-->

**Expected behaviour:** Step Tabs can be renamed

**Actual behaviour:** Step Tabs can't be renamed, default to 'Step 1', 'Step 2', etc

**Reproduces how often:** 100%

**Comment by Auriga2** [comment]
The current version doesn't store the step caption in the json template when saving. Added a new field called "step", but there's a backward compatibility issue if the user tries to open a new template with a previous version of Consty.
![image](https://user-images.githubusercontent.com/64826928/149244966-9cf00cf4-d42b-4817-a65b-d84f1c43431c.png)


```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "step" (class au.gov.asd.tac.constellation.views.dataaccess.api.DataAccessUserPreferences), not marked as ignorable (2 known properties: "plugins", "global"])
 at [Source: (File); line: 2, column: 13] (through reference chain: java.util.ArrayList[0]->au.gov.asd.tac.constellation.views.dataaccess.api.DataAccessUserPreferences["step"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3433)
[catch] at au.gov.asd.tac.constellation.utilities.genericjsonio.JsonIO.lambda$loadJsonPreferences$1(JsonIO.java:327)
	at au.gov.asd.tac.constellation.utilities.genericjsonio.JsonIO.loadJsonPreferences(JsonIO.java:464)
	at au.gov.asd.tac.constellation.utilities.genericjsonio.JsonIO.loadJsonPreferences(JsonIO.java:325)
	at au.gov.asd.tac.constellation.utilities.genericjsonio.JsonIO.loadJsonPreferences(JsonIO.java:356)
	at au.gov.asd.tac.constellation.views.dataaccess.io.DataAccessParametersIoProvider.loadParameters(DataAccessParametersIoProvider.java:106)
	at au.gov.asd.tac.constellation.views.dataaccess.components.OptionsMenuBar.lambda$init$0(OptionsMenuBar.java:112)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.MenuItem.fire(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by GammaVel** [comment]
I've gotten a few unhandled exceptions here which needs investigating that seem to have a different  number in ForkJoinPool.commonPool-worker-7 but apart from that very similar. 

1. Runtime error when clicking on plus for new tab - one off
2.  Runtime error when closing tabs in a different order (X2)  that were saved to a template
3.  Runtime error when click on the tab names here that were loaded from a template

java.lang.IllegalStateException: Not on FX application thread; currentThread = ForkJoinPool.commonPool-worker-7
	at javafx.graphics/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$3.onProposedChange(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.updateChildren(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.lambda$new$11(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
[catch] at javafx.base/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at javafx.controls/javafx.scene.control.Labeled.setText(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.updateDisplayText(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.updateDisplayNode(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.lambda$new$2(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at javafx.base/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.controls/javafx.scene.control.ComboBoxBase.setPromptText(Unknown Source)
	at au.gov.asd.tac.constellation.plugins.gui.ValueInputPane.recentValuesChanged(ValueInputPane.java:309)
	at au.gov.asd.tac.constellation.plugins.parameters.RecentParameterValues.fireChangeEvent(RecentParameterValues.java:111)
	at au.gov.asd.tac.constellation.plugins.parameters.RecentParameterValues.storeRecentValue(RecentParameterValues.java:66)
	at au.gov.asd.tac.constellation.views.dataaccess.components.DataAccessTabPane.lambda$storeParameterValues$14(DataAccessTabPane.java:440)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.views.dataaccess.components.DataAccessTabPane.lambda$storeParameterValues$17(DataAccessTabPane.java:440)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by Auriga2** [comment]
@GammaVel, as in my last comment above, https://github.com/constellation-app/constellation/issues/1608 is logged to handle this 'java.lang.IllegalStateException`.

**Comment by GammaVel** [comment]
Thanks @Auriga2, I made a comment there for retesting on the scenarios where I am consistently seeing the error.
