### ISSUE TITLE
IllegalStateException in Data access view when multiple tabs are added

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1608]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
In v2.5.0 , Data access view throws the below exception if the user loads a template containing few tabs and then immediately click on Tab2. The tabs should have plugins selected, and if you wait a while before clicking on Tab 2, the exceptions is not thrown. 
Sometimes the exception is thrown when a new tab is added and clicked on it immediately, without loading any template.
```
java.lang.IllegalStateException: Not on FX application thread; currentThread = ForkJoinPool.commonPool-worker-3
	at javafx.graphics/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$3.onProposedChange(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.updateChildren(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.lambda$new$11(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
[catch] at javafx.base/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at javafx.controls/javafx.scene.control.Labeled.setText(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.updateDisplayText(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.updateDisplayNode(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.lambda$new$2(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(Unknown Source)
	at javafx.base/javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at javafx.controls/javafx.scene.control.ComboBoxBase.setPromptText(Unknown Source)
	at au.gov.asd.tac.constellation.plugins.gui.ValueInputPane.recentValuesChanged(ValueInputPane.java:309)
	at au.gov.asd.tac.constellation.plugins.parameters.RecentParameterValues.fireChangeEvent(RecentParameterValues.java:111)
	at au.gov.asd.tac.constellation.plugins.parameters.RecentParameterValues.storeRecentValue(RecentParameterValues.java:66)
	at au.gov.asd.tac.constellation.views.dataaccess.components.DataAccessTabPane.lambda$storeParameterValues$13(DataAccessTabPane.java:381)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.views.dataaccess.components.DataAccessTabPane.lambda$storeParameterValues$14(DataAccessTabPane.java:379)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

### Steps to Reproduce
Sometimes the exception is thrown when a new tab is added and clicked on it immediately, without loading any template. 
1.  Open DAV, select 4-5 plugins, leaving the default parameters. 

2.  Open a second tab,  and click on it immediately. If no exception is thrown, select a few more plugins and open a new tab and click immediately.

If that doesn't work, use a template as below:

1.  Open DAV, select `Extend from Pajek File` plugin. 

2.  Open a second tab,  select `Extend from Pajek File` plugin. 

3.  Save the template and close all tabs.

4.  Load the saved Template and quickly click on the `Step 2` tab as soon as it's loaded.

**Expected behaviour:** No exceptions thrown

**Actual behaviour:** Above exception is thrown

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
Thanks @antares1470 and @Auriga2. Just adding that I have observed this appear when I add a new tab and rename the first one in a quick succession. This is very repeatable.

**Comment by GammaVel** [comment]
This is looking great, thanks @spica198 for resolving the issues here. I tried out the same steps that were causing me the error with renaming tabs and it is no longer happening. I also created a new template, saved and reopened it and clicked on the other tabs to see if there was an error, this worked. Thanks again.
