### ISSUE TITLE
File Importer does not set some Source and Destination options when loading a template

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1652]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
When loading a template,  `Destination` and `Files Include Headers` options do not set as in the template, although they are applied and ` File Parser` is trying to match for other types of files as well.

E.g. 
1. Import a file and set the `Destination` option to `New Analytic Graph`. Then try to load a template with `destination` as `VisualSchemaFactory`. The `Destination`  field clears but when imported, a new visual graph is created as expected. The field should be displayed as  `New Visual Graph` instead of clearing. Note that this works sometimes, but can be reproduced always if the drop down is manually selected before loading the template.

2. Import a file and set the `Files Include Headers`  option. Then load a template with that option set to false. It's applied in the preview (you can see it by the column headers) but the option does not set to false. If this file is now removed and a different file is imported, the option is still set but data is imported as if it was not set.  Visually setting the option should be enough to fix the problem here.
![image](https://user-images.githubusercontent.com/64826928/155273345-8fc1540e-970e-4cbe-bdb8-768a8b8d27a1.png)

3. If you open a file and load a template containing a different File Parser, it still tries to load it incorrectly. I guess we should display a warning message and avoid loading.
![image](https://user-images.githubusercontent.com/64826928/155266458-66564ae9-492d-4c17-b5f9-adbc5c6ea831.png)

### Steps to Reproduce

As above.

**Expected behaviour:** Options should display as in the template

**Actual behaviour:** Options do not display as in the template

**Reproduces how often:** 100%

**Comment by GammaVel** [comment]
I am receiving a runtime error under the following conditions:

1. I have made a new template for using during the import. The default graph type is "New Analytic Graph"
2. I have tested it out so I know it works with my rideshare data
3. I added in a rideshare datafile, using default options. I changed the graph type from "New Analytic Graph" to "New Visual Graph" 
4. I clicked load template which has the graph set to New Analytic graph and I get the following run time error:

java.lang.NullPointerException
	at au.gov.asd.tac.constellation.plugins.importexport.delimited.ImportDelimitedIO.loadParameterFile(ImportDelimitedIO.java:285)
	at au.gov.asd.tac.constellation.plugins.importexport.delimited.ImportDelimitedIO.loadParameters(ImportDelimitedIO.java:221)
	at au.gov.asd.tac.constellation.plugins.importexport.delimited.DelimitedImportPane.lambda$new$0(DelimitedImportPane.java:43)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$4(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$5(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by antares1470** [comment]
@GammaVel the issue here is to do with the schemas themselves. The attributes you can pick from are defined by the schemas you're trying to import and in this case, the type attribute is not a part of bare schema (which has no attributes) nor the visual schema. I think this is an issue we can address, but I think it might be a separate issue the one here

**Comment by Auriga2** [comment]
@GammaVel Yeah sounds like a separate issue, but I'll have to debug and see what the exact problem is. Appreciate if you can share that file to recreate the issue.

**Comment by Auriga2** [comment]
Managed to recreate the exception @GammaVel.

**Comment by Auriga2** [comment]
@GammaVel This exception is thrown when the template doesn't contain the required Source details such as `Parser`, `schema_init` etc. The only way that can happen is in a corrupted file, or if you used an older template file. Can you please confirm whether this is the case, or if this template works with a different set up, in case the exception is thrown for a different cause? Because when I recreated, I simply deleted some fields in the template file.

**Comment by Auriga2** [comment]
The root cause of the exception is the same in all scenarios, which is missing json fields the code is trying to access in the template.

In one scenario I could recreate with the provided template where `Content` is considered as a custom attribute (with AnalyticSchemaFactory ). The template has it as this:
```
{
        "column_label" : "Trip Duration",
        "attribute_label" : "Content",
        "translator" : "au.gov.asd.tac.constellation.plugins.importexport.translator.DefaultAttributeTranslator",
        "translator_args" : null,
        "default_value" : null
 }
```
It's throwing the exception because the code assumes the `attribute_type` and `attribute_description` fields are present in the template,  for user added attributes, but Content should be considered an `autoAddedTransactionAttributes`. - Not sure why.

The second scenario where the exception is thrown when the destination switches was due to a threading issue. The schemas of the updated destination wasn't applied in the `importController` by the time they are accessed in the `ImportDelimitedIO.loadParameterFile`, because it was performed inside a `Platform.runLater` in the `Import Controller`. - This is fixed by removing the controller updates from that thread.

**Comment by Auriga2** [comment]
The actual cause of 1 above should have been because of some bugs in the code:

a) where the 'Show all schema attributes' option was not reflecting properly, allowing creation of an incorrect template. In the example template we used (as in above screen captures) `show_all_schema_attributes` is `false` with Analytic schema, but it has allowed creation of a template with `Content` as an Auto attribute. Instead it should have been saved as a user added attribute with `attribute_type` and `attribute_description` fields, unless `show_all_schema_attributes` is `true` 

b) templates were not adhering to the 'Show all schema attributes' option saved in the template. It lead the template to be loaded with incorrect/missing schemas which were then considered as User added Attributes.

So although the exceptions were thrown due to missing json fields, the real cause were other bugs. Hence I added a check for json field availability before accessing them, displaying a warning message indicating the template could be of incorrect format.

**Other issues noted in v2.6:**

3. Preference to show or hide all graph schema attributes is the same across File importer and Database importer. I believe it's a bug that only the value set in the File importer gets saved and applied to both importers when reloading constellation.

4. User added attributes don't seem to work consistently. They retain sometimes, when loading some templates, but only until a few loads (of the same template) and then suddenly disappear. (Random nature probably due to 2 above)
- They clear when the destination (schema) changes and doesn't pop back when the previous schema is selected again.
- They clear when consty is closed
- This comment implies they should  be cleared when loading a template. It makes sense because we'll also load any user added attributes added in the template anyway. If we keep them, need to consider what to do when there are different user added attributes with the same name etc. (as discussed)
`     //Clearing the manually added attributes removes them when loading a template.
        // The destination is set with clearmanuallyAdded true before loading the
        // template, so there are no other left-over attributes to clear out after
        // loading a template.`

**Comment by Auriga2** [comment]
For b) above feels like using default values such as "attribute_type" = "String" and "attribute_description" : "" and proceeding is incorrect because the attribute_type could be anything. So I proceed without adding the faulty custom attribute and display the warning message mentioning that , so the user can add it manually or fix the template.

**Comment by Auriga2** [comment]
For c) above, the code currently removes all user added attributes when a template is loaded, but adds back any previously allocated attributes if they are missing. I'll keep that behavior for now, but we can change later if that should be changed. A good point to add in documentation as it's confusing otherwise.

**Comment by Auriga2** [comment]
Noticed that some of these issues affect Database importer as well. But there are some other issues:
1. `Initialize with schema` is not added in the UI but saved `True` in the template- should we add it in the UI or should this be removed from the template?
2. `Show all schema attributes` is not saved in the template and not applied when loading-Can fix

**Comment by GammaVel** [comment]
I get a different runtime error when switching between the graph types and I have a clear reproducer for this defect with the date time field.  This is independent of the template issue. I will make a new issue.
![image](https://user-images.githubusercontent.com/83679004/179454714-36f8c7dd-52fc-4ee3-abbf-e56ba9fbb460.png)

**Comment by GammaVel** [comment]
Update to the above - I saw this error message but not with the same reproducer. There is some condition that is triggering it, I am just not sure exactly what it is.  

I have detected a few unrelated issues when looking at this issue that I have created new tickets for consideration in future development.
