### ISSUE TITLE
Welcome Page - Open Data Access View button not working

### ISSUE THREAD

**Issue by Auriga2** [constellation-app/constellation#1656]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
`Open Data Access View` functionality in the Welcome Page is not working. When clicked on for the first time, below exception is thrown (After Constellation is loaded). Subsequent clicks don't do anything. Same behavior is v2.5
```
java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.views.dataaccess.panes.DataAccessViewTopComponent starting from SystemClassLoader[118 modules] with possible defining loaders [ModuleCL@40c67151[au.gov.asd.tac.constellation.views.dataaccess]] and declared parents [org.netbeans.MainImpl$BootClassLoader@3dd3bcd, org.netbeans.JarClassLoader@797184d7, ModuleCL@437cef03[org.netbeans.api.annotations.common], ModuleCL@443aaa6f[org.openide.awt], ModuleCL@34d4f840[org.netbeans.api.progress], ModuleCL@6ff60e85[org.netbeans.api.progress.nb], ModuleCL@4ed355c4[org.openide.dialogs], ModuleCL@1adc5b16[org.openide.nodes], ModuleCL@26cd9ef6[org.openide.windows], ModuleCL@14c29e9f[org.netbeans.libs.batik.read], ...101 more]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:769)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.openide.windows.TopComponent$Replacer.readObject(TopComponent.java:1821)
Caused: java.io.IOException
	at org.openide.windows.TopComponent$Replacer.readObject(TopComponent.java:1881)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.readSerial(XMLSettingsSupport.java:546)
	at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.instanceCreate(XMLSettingsSupport.java:578)
	at org.netbeans.modules.settings.convertors.SerialDataConvertor$SettingsInstance.instanceCreate(SerialDataConvertor.java:401)
[catch] at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:547)
	at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:657)
	at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
	at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:1002)
	at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:270)
	at au.gov.asd.tac.constellation.views.welcome.plugins.DataAccessViewWelcomePlugin.lambda$run$0(DataAccessViewWelcomePlugin.java:64)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

### Steps to Reproduce

Open constellation and click on `Open Data Access View` button in the Welcome Page.

**Expected behaviour:** `Data Access View` is loaded
**Actual behaviour:** An exception is thrown and DAV is not loaded

**Reproduces how often:** 100%

**Comment by Delphinus8821** [comment]
@Auriga2 This can be fixed by running the reset.bat script that is included with the release version of Constellation.

**Comment by Auriga2** [comment]
Yes that fixed the issue. Do we have to manually run it with every build? Would all users know that?

**Comment by Delphinus8821** [comment]
It will need to be manually run whenever a view has been rewritten.

**Comment by GammaVel** [comment]
Thanks @Delphinus8821 and @Auriga2 for contributing to this issue.  This has now been added to the list of known issues https://github.com/constellation-app/constellation/wiki/Known-Issues

**Comment by Auriga2** [comment]
@GammaVel Shouldn't it say `since v2.5`?
