### ISSUE TITLE
Can't run Offline Help and Rest Server in same session

### ISSUE THREAD

**Issue by antares1470** [constellation-app/constellation#1672]
### Prerequisites

- [x] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The Offline help and Rest server are trying to connect through the same port. This means that if you try to use one after the other in the same session, you'll get an exception.
```
java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:336)
Caused: java.io.IOException: Failed to bind to localhost/127.0.0.1:1517
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:341)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:302)
	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:401)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.eclipse.jetty.server.Server.doStart(Server.java:397)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at au.gov.asd.tac.constellation.webserver.WebServer.start(WebServer.java:199)
Caused: java.lang.RuntimeException
	at au.gov.asd.tac.constellation.webserver.WebServer.start(WebServer.java:222)
	at au.gov.asd.tac.constellation.webserver.StartRestServerAction.actionPerformed(StartRestServerAction.java:39)
```

As a user, you can of course just change the port the rest server listens on via preferences and this would resolve the issue but I feel we should probably not have both of them listening on the same port by default rather than leaving it to users to have to manually fix it themselves

### Steps to Reproduce

1. Open Constellation
2. Open a help page though offline help
3. Try to start the rest server (Tools -> Start REST Server)

**Expected behaviour:** Rest server starts

**Actual behaviour:** Rest server doesn't start, exception thrown

**Reproduces how often:** 100%

### Additional Information

The above stack trace is one you get following the specified reproducer. You get a similar exception if you try doing it the other way around (start rest server and then open a help page through offline help)

**Comment by GammaVel** [comment]
Keen to take a look at this one however the latest nightly build has expired. Just trying to rerun it manually.

**Comment by GammaVel** [comment]
I've got a copy of the latest nightly build which includes the fix and this is working brilliantly!  Thank you @Delphinus8821 for fixing this one up.
