### ISSUE TITLE
Text inputs into numeric field - runtime error shown

### ISSUE THREAD

**Issue by GammaVel** [constellation-app/constellation#1687]
### Prerequisites

- [X] Put an X between the brackets on this line if you have done all of
    the following:

    -   Running the latest version of Constellation

    -   Attached the ***Support Package*** via `Help` &gt;
        `Support Package`

    -   Checked the FAQs:
        https://github.com/constellation-app/constellation/wiki/FAQ

    -   Checked that your issue isn’t already filed:
        https://github.com/constellation-app/constellation/issues

    -   Checked that there is not already a module that provides the
        described functionality:
        https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

On the Data access view and analytic view that are several fields which only take numbers as input. For example, the Threshold on the Remove Nodes on the data access view take numbers. If I change this to be text (such as aa) a runtime error is thrown consistently (see below for full details). 

### Steps to Reproduce

1.  Open any graph and go to the Data Access view
2.  Look for number field and change it to text
3.  Press Go > Runtime error is displayed
4.  Repeat with some other fields that are expecting numbers
5. Repeat with the analytic view > same behaviour is seen there

**Expected behaviour:** \Invalid input warning is displayed instead of runtime error

**Actual behaviour:**Runtime error

**Reproduces how often:** 100%

### Additional Information

![image](https://user-images.githubusercontent.com/83679004/166184554-20545a5f-384b-40c4-9e0b-13c6f36759e1.png)
java.lang.NumberFormatException: For input string: "aa"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.valueOf(Unknown Source)
	at javafx.base/javafx.util.converter.IntegerStringConverter.fromString(Unknown Source)
	at javafx.base/javafx.util.converter.IntegerStringConverter.fromString(Unknown Source)
	at javafx.controls/javafx.scene.control.Spinner.commitValue(Unknown Source)
[catch] at javafx.controls/javafx.scene.control.Spinner.lambda$new$3(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Node$FocusedProperty.notifyListeners(Unknown Source)
	at javafx.graphics/javafx.scene.Node.setFocused(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.setWindowFocused(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.lambda$new$0(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.graphics/javafx.stage.Window.setFocused(Unknown Source)
	at javafx.graphics/javafx.stage.Window$1.setFocused(Unknown Source)
	at javafx.graphics/com.sun.javafx.stage.WindowHelper.setFocused(Unknown Source)
	at javafx.graphics/com.sun.javafx.stage.WindowPeerListener.changedFocused(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedStage.lambda$setFocused$4(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedStage.lambda$notifyStageListener$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedStage.notifyStageListener(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedStage.lambda$notifyStageListenerLater$1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by GammaVel** [comment]
Refer to the comments in #48. This can't easily be fixed in Constellation.

**Comment by GammaVel** [comment]
Thank you @OrionsGuardian for fixing this up. This is working nicely in the Data Access view and the Analytic view. No more runtime errors!
