### ISSUE TITLE
Null Pointer when showing transaction in New Table View

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#191]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Selecting a transaction to view in New Table View will result in a Null Pointer error
```java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.showSelected(TableViewTopComponent.java:214)
	at au.gov.asd.tac.constellation.views.tableview2.ShowInTableViewContextMenuProvider.lambda$selectItem$0(ShowInTableViewContextMenuProvider.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to Reproduce

1. Open new Graph
2. Create Sphere Graph (Or any graph)
3. Right click a transaction ans select Show In New Table View

**Expected behaviour:** 
New Table view to open and display details

**Actual behaviour:** 
Null pointer error dialog

**Reproduces how often:** 
100%

### Additional Information

N/A

**Comment by formalhaut69** [comment]
This is what's causing the null pointer, specifically line 214. 
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewTopComponent.java#L212-L218

**Comment by formalhaut69** [comment]
We could remove this code since it's not working but it might have a purpose and isn't functioning as expected.

**Comment by arcturus2** [comment]
@formalhaut69 good pickup. When I opened that class NetBeans told me that line 212 is de-referencing a null pointer. Should the logic instead be:

```java
 if (stateLock != null) 
```

Would you be able to test and PR a fix if you have time?

**Comment by formalhaut69** [comment]
@arcturus2 Sure, no problem.
