### ISSUE TITLE
Null pointer when changing the time zone in the timeline view on a new graph

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#193]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Changing the timezone on the timeline view on a new graph causes a null pointer exception when the graph is closed. 
```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.timeline.TimelineTopComponent.persistStateToGraph(TimelineTopComponent.java:636)
	at au.gov.asd.tac.constellation.views.timeline.TimelineTopComponent.updateTimeZone(TimelineTopComponent.java:568)
	at au.gov.asd.tac.constellation.views.timeline.TimelinePanel.lambda$createToolBar$4(TimelinePanel.java:489)
[catch] at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:102)
	at javafx.scene.control.ComboBox$ComboBoxSelectionModel.lambda$new$0(ComboBox.java:494)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:72)
	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
	at javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:68)
	at javafx.scene.control.SingleSelectionModel.updateSelectedIndex(SingleSelectionModel.java:215)
	at javafx.scene.control.SingleSelectionModel.select(SingleSelectionModel.java:149)
	at javafx.scene.control.SingleSelectionModel.select(SingleSelectionModel.java:124)
	at au.gov.asd.tac.constellation.views.timeline.TimelinePanel.setTimeZone(TimelinePanel.java:669)
	at au.gov.asd.tac.constellation.views.timeline.TimelineTopComponent$2.run(TimelineTopComponent.java:358)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce

1. Make a new analytic graph
2. Open the timeline view
3. Change the timezone
4. Close the graph

**Expected behaviour:** 
The graph closes without a null pointer.

**Actual behaviour:**
The graph closes with a null pointer exception. 

**Reproduces how often:** 
100%

### Additional Information

N/A

**Comment by formalhaut69** [comment]
Line 358 is causing the null pointer. It calls the setTimeZone method and attempts to set it back to the default UTC time zone. For some reason, the error only occurs if the time zone was previously set to something other than the UTC time zone. I'm not entirely sure what the purpose of this line of code is either, my guess is that it was meant to set the time zone back to UTC as part of refreshing the timeline panel. If this is the case, a solution could be to just remove this line of code since the time zone box gets refreshed back to UTC elsewhere. Any other suggestions would be appreciated. 
https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreTimeline/src/au/gov/asd/tac/constellation/views/timeline/TimelineTopComponent.java#L336-L366

**Comment by serpens24** [comment]
updateTimeZone is being called to update the timezone ... within this mmethod is a call to persistStateToGraph() which is expecting graphNode to exist - this isn't the case as the graph has closed before the call is made. Additionally, IF the code was to make it past this point, the method populatefromGraph() is also called, and is assuming the supplied graph parameter is non-null.

Becausde both of these methods can be called from elsewhere, the best option is to protect them internally,.... ie - add checks for null into persistStateToGraph() and populatefromGraph() and gracefully handle this case. Both methods can handle returning without action, so this is the most obvious approach.
