### ISSUE TITLE
The training solutions make the search bar unusable

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#198]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
When the training solutions are imported, an illegal argument exception is always thrown when trying to use the search bar. This makes it completely unusable.

### Steps to Reproduce

1. Import the training solutions
2. Run the Training solutions Module suite 
3. Type something into the search bar

**Expected behaviour:** The search bar functions normally

**Actual behaviour:** An illegal argument exception is thrown

**Reproduces how often:** 100%

### Additional Information
`java.lang.IllegalArgumentException: view is invalid
	at javax.help.search.MergingSearchEngine.merge(MergingSearchEngine.java:91)
	at org.netbeans.modules.javahelp.JavaHelp.createSearchEngine(JavaHelp.java:213)
	at org.netbeans.modules.javahelp.JavaHelpQuery.createSearchEngine(JavaHelpQuery.java:154)
	at org.netbeans.modules.javahelp.JavaHelpQuery.search(JavaHelpQuery.java:104)
	at org.netbeans.modules.javahelp.JavaHelpQuickSearchProviderImpl.evaluate(JavaHelpQuickSearchProviderImpl.java:70)
	at org.netbeans.modules.quicksearch.CommandEvaluator$3.run(CommandEvaluator.java:265)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
	at org.openide.util.RequestProcessor.post(RequestProcessor.java:420)
	at org.netbeans.modules.quicksearch.CommandEvaluator.runEvaluation(CommandEvaluator.java:262)
	at org.netbeans.modules.quicksearch.CommandEvaluator.evaluate(CommandEvaluator.java:111)
	at org.netbeans.modules.quicksearch.QuickSearchPopup$1.run(QuickSearchPopup.java:206)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)`

**Comment by formalhaut69** [comment]
On second glance, this issue doesn't seem to be within the scope of constellation. Nothing in the stack trace points to code from constellation. 

It is unusual though that this issue only occurs when the training solutions are imported. One possible theory that I have that would be an issue on our end is that the method evaluate() within the netbeans quicksearch module isn't getting overridden properly once the training solutions are imported. This might explain why an illegal argument exception is thrown because the user is searching for something that can't be processed by netbeans' module.

**Comment by formalhaut69** [comment]
@arcturus2 based on what I found, do you think we should close this issue?

**Comment by arcturus2** [comment]
OK to close this for now @formalhaut69 and if it comes up then look at it again. Cheers.
