### ISSUE TITLE
Map View doesn't get garbage collected properly which can crash Constellation

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#218]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
Constellation will become unusable if the map view is resized too much. This occurs because the map view doesn't get garbage collected properly causing the graphics buffer to fill up until it overflows. 

### Steps to Reproduce

1. Open the map view
2. Resize it constantly 

**Expected behaviour:** The map view resizes without issue

**Actual behaviour:** The graphics buffer fills up until constellation becomes unusable  

**Reproduces how often:** 100%

### Additional Information

```
com.jogamp.opengl.GLException: GL-Error 0x505 while creating mutable storage for target 0x8892 -> buffer 1 of size 64 with data java.nio.DirectFloatBufferU[pos=0 lim=256 cap=256]
	at jogamp.opengl.GLBufferObjectTracker.createBufferStorage(GLBufferObjectTracker.java:176)
	at jogamp.opengl.gl4.GL4bcImpl.glBufferData(GL4bcImpl.java:40258)
	at processing.opengl.PJOGL.bufferData(PJOGL.java:1149)
	at processing.opengl.PGraphicsOpenGL.updatePolyBuffers(PGraphicsOpenGL.java:1230)
	at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2370)
	at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2314)
	at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:1480)
	at de.fhpotsdam.unfolding.mapdisplay.OpenGLMapDisplay.postDraw(OpenGLMapDisplay.java:114)
	at de.fhpotsdam.unfolding.mapdisplay.Java2DMapDisplay.draw(Java2DMapDisplay.java:406)
	at de.fhpotsdam.unfolding.UnfoldingMap.draw(UnfoldingMap.java:366)
	at au.gov.asd.tac.constellation.views.mapview.MapViewTileRenderer.draw(MapViewTileRenderer.java:376)
	at processing.core.PApplet.handleDraw(PApplet.java:2426)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
[catch] at java.util.TimerThread.run(Timer.java:505)
```

**Comment by aldebaran30701** [comment]
Adding this to [Known Issues](https://github.com/constellation-app/constellation/wiki/Known-Issues) and closing this in the meantime. Review the entry to get an idea of why it will not be fixed.
