### ISSUE TITLE
Upgrade to latest NetBeans and Java (Master Ticket)

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#219]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

It's been a while since we had a go at upgrading Constellation to the latest version of NetBeans and Java. This is a master ticket to get those interested in helping out with the upgrade up to speed on where we are at.

The work is currently tracked in branch `nb11jdk11migration-master`. The plan is to still try upgrading to NetBeans 11 (the latest is 11.2) and Java 11. Noted that there is Java 14 but l'll suggest taking smaller steps to get it working in Java 11 unless there are fixes with issues we currently have with 11.

Note that we may want to stick with the Zulu version of Java because it worked without needing to make changes to the code from Oracle Java 11 which we had used previously. We tried OpenJDK + OpenJFX, RedHat's Java and Amazon's Java called Corretto. They all had issues with JavaFX. Therefore we went with Zulu which had packaged Java with JavaFX. Looking at https://cdn.azul.com/zulu/bin/ I've got a concern because I've noticed they no longer package JavaFX with the JDK. The latest version which has JavaFX bunddled in is zulu11.35.15 but their latest is  zulu11.37.17. Let's see 😟 .

Also noting that it has been 6 months since the last attempt so maybe things have changed and we can just use OpenJDK and OpenJFX!

NetBeans has now also included an installer with 11.2 which is a problem now that it get's installed into C:\Program Files by default which makes it harder to replace `org-netbeans-modules-javahelp.jar` into 'C:\Program Files\NetBeans-11.2\netbeans\platform\modules' and `jhall-2.0_05.jar` into 'C:\Program Files\NetBeans-11.2\netbeans\platform\modules\ext'. At least when I tried to do it on my Amazon Workspace it failed. I had to manually override the files and comment out this block in `build.xml`

https://github.com/constellation-app/constellation/blob/47d5dd80f85c65988027b01e13547a43e0048401/build.xml#L67-L80

Ideally we shouldn't need to replace jar files provided by NetBeans and this was more of a last resort to get things compiling and then figure out how to fix it properly. The related ticket regarding these 2 jars is Issue https://github.com/constellation-app/constellation/issues/15.

During testing we identified issues with JOGL and it turned out we needed a newer version compiled to Java 11 to be available. The new jar is now available and needs to be integrated. The related ticket for this work is Issue https://github.com/constellation-app/constellation/issues/69.

There is a similar issue with another jar called `processing-core.jar` which is used by the Map View (Unfolding Maps). The ticket for this is Issue https://github.com/constellation-app/constellation/issues/76.

Once these things are sorted then we need to do a lot of testing. One bug is that the graph view seems to be offset when scaling is enabled in Windows on a Hi DPI screen. See Issue https://github.com/constellation-app/constellation/issues/11 for the details.

To get Constellation running refer to the `README.md` in the `nb11jdk11migration-master` branch which is located https://github.com/constellation-app/constellation/blob/nb11jdk11migration-master/README.md as it has links to the correct versions of NetBeans and Zulu Java.

**Comment by aldebaran30701** [comment]
OpenJFX is now available at https://search.maven.org/search?q=g:org.openjfx%20AND%20a:javafx&core=gav Through maven central. This means when we migrate to this build, we can just pull the dependency from maven.

**Comment by aldebaran30701** [comment]
#15 mentioned currently does not have the correct version available on maven to obtain. I added dependencies for the other versions of jhall and help modules. I renamed them to match current NB Platform names but came up with the same errors others in the nested tickets found.

It seems that we may only have a few choices; 
 - Add exact files to maven central for dependency download
 - Not use Java Help
 - Leave it downloading from the GitHub repo which it currently points at
 - Add files to 3rd party dependencies instead of a self managed repo by rsabhi.

**Comment by arcturus2** [comment]
> Add files to 3rd party dependencies instead of a self managed repo by rsabhi.

I've done that now. For some reason I thought I had updated build.xml too...obviously didn't check it in. You can get them from the 3rd party libs instead.

**Comment by arcturus2** [comment]
@aldebaran30701  I sent through a PR to use our 3rd party repo instead https://github.com/constellation-app/constellation/pull/275

I did some testing on the NB 11 branch and besides the offset issue which seems to occur on the graph and map view, there was an issue with some NoClassDefFound when I played with views like the attribute editor and other views that needed a scroll bar.

For example I get this if I try to change the Node type from the attribute editor. I got this on the latest version of NB11.3 and Java too. Are you getting this error?

```
SEVERE [javafx.scene.control]: Failed to load skin 'com.sun.javafx.scene.control.skin.ListCellSkin' for control VertexTypeEditorFactory$VertexTypeEditor$1@4d2f6652[styleClass=cell indexed-cell list-cell]'Online Location'
java.lang.ClassNotFoundException: com.sun.javafx.scene.control.skin.ListCellSkin
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at javafx.controls/javafx.scene.control.Control.loadClass(Control.java:124)
[catch] at javafx.controls/javafx.scene.control.Control.loadSkinClass(Control.java:720)
	at javafx.controls/javafx.scene.control.Control$5.invalidated(Control.java:680)
	at javafx.base/javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.base/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
	at javafx.graphics/javafx.css.StyleableStringProperty.set(StyleableStringProperty.java:83)
	at javafx.controls/javafx.scene.control.Control$5.set(Control.java:672)
	at javafx.graphics/javafx.css.StyleableStringProperty.applyStyle(StyleableStringProperty.java:69)
	at javafx.graphics/javafx.css.StyleableStringProperty.applyStyle(StyleableStringProperty.java:45)
	at javafx.graphics/javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:787)
	at javafx.graphics/javafx.scene.Node.doProcessCSS(Node.java:9647)
	at javafx.graphics/javafx.scene.Node.access$900(Node.java:398)
	at javafx.graphics/javafx.scene.Node$1.doProcessCSS(Node.java:471)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSSImpl(NodeHelper.java:192)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSSImpl(ParentHelper.java:93)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSS(ParentHelper.java:63)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1366)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:886)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9529)
	at javafx.graphics/javafx.scene.Node.applyCss(Node.java:9616)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1715)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:2042)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.scrollPixels(VirtualFlow.java:1586)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow$1.handle(VirtualFlow.java:386)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow$1.handle(VirtualFlow.java:328)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene.processGestureEvent(Scene.java:1927)
	at javafx.graphics/javafx.scene.Scene.access$5000(Scene.java:172)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.scrollEvent(Scene.java:2666)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$scrollEvent$6(EmbeddedScene.java:311)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$scrollEvent$7(EmbeddedScene.java:307)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by arcturus2** [comment]
Constellation running on NB11.3 with Flat Dark LAF. Needs tweaking but has potential!

![image](https://user-images.githubusercontent.com/39325530/75914220-7e9daa00-5ea8-11ea-94d5-c6444994fd16.png)

**Comment by aldebaran30701** [comment]
New master ticket #387 
Closing this.
