### ISSUE TITLE
The Map View constantly resets itself

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#24]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

Resizing the Map View forces it to completely reset itself - this gives you a way to deal with some GL related issues that can occur. I have noticed on certain displays that the Map View gets into a state where it constantly resets itself, making it impossible to use. 

An exception when you continuously resize the map view is the following exception:
`
SEVERE [global]
java.lang.RuntimeException: Number of texture units not supported by this hardware (or driver) Read http://wiki.processing.org/w/OpenGL_Issues for help.
    at processing.opengl.PGL.bindTexture(PGL.java:3235)
    at processing.opengl.Texture.allocate(Texture.java:1147)
    at processing.opengl.Texture.init(Texture.java:213)
    at processing.opengl.Texture.<init>(Texture.java:171)
    at processing.opengl.PGraphicsOpenGL.loadTextureImpl(PGraphicsOpenGL.java:5921)
    at processing.opengl.PGraphicsOpenGL.initOffscreen(PGraphicsOpenGL.java:6602)
    at processing.opengl.PGraphicsOpenGL.beginOffscreenDraw(PGraphicsOpenGL.java:6654)
    at processing.opengl.PGraphicsOpenGL.beginDraw(PGraphicsOpenGL.java:1461)
    at de.fhpotsdam.unfolding.mapdisplay.Java2DMapDisplay.draw(Java2DMapDisplay.java:351)
    at de.fhpotsdam.unfolding.UnfoldingMap.draw(UnfoldingMap.java:366)
    at au.gov.asd.tac.constellation.mapview.MapViewTileRenderer.draw(MapViewTileRenderer.java:525)
    at processing.core.PApplet.handleDraw(PApplet.java:2437)
    at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:859)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
    at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
    at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
    at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
    at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
    at java.util.TimerThread.mainLoop(Timer.java:555)
[catch] at java.util.TimerThread.run(Timer.java:505) {code}
{code:java}
SEVERE [global]
java.lang.NullPointerException
    at au.gov.asd.tac.constellation.display.renderer.batcher.Batch.connectIntBuffer(Batch.java:475)
    at au.gov.asd.tac.constellation.display.renderer.batcher.IconBatcher.lambda$updateIcons$1(IconBatcher.java:122)
    at au.gov.asd.tac.constellation.display.renderer.batcher.SceneBatcher.lambda$updateIntBufferTask$0(SceneBatcher.java:160)
    at au.gov.asd.tac.constellation.display.renderer.GraphRenderable.lambda$addTaskIfReady$0(GraphRenderable.java:115)
    at au.gov.asd.tac.constellation.display.renderer.GraphRenderable.lambda$update$29(GraphRenderable.java:376)
    at java.util.ArrayList.forEach(Unknown Source)
    at au.gov.asd.tac.constellation.display.renderer.GraphRenderable.update(GraphRenderable.java:375)
    at au.gov.asd.tac.constellation.display.renderer.GLRenderer.lambda$display$2(GLRenderer.java:164)
    at java.util.ArrayList.forEach(Unknown Source)
    at au.gov.asd.tac.constellation.display.renderer.GLRenderer.display(GLRenderer.java:163)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
    at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1424)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
Caused: com.jogamp.opengl.GLException: Caught NullPointerException: null on thread AWT-EventQueue-0
    at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1438)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused: java.lang.RuntimeException
    at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
    at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
    at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:201)
    at com.jogamp.opengl.Threading.invokeOnOpenGLThread(Threading.java:202)
    at com.jogamp.opengl.Threading.invoke(Threading.java:221)
    at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:505)
    at au.gov.asd.tac.constellation.display.renderer.GLVisualProcessor.performVisualUpdate(GLVisualProcessor.java:195)
    at au.gov.asd.tac.constellation.visualsupport.display.VisualProcessor.lambda$update$0(VisualProcessor.java:211)
`

The Map view can caused Constellation to run sluggishly and can do with a revisit to how things could be improved. An immediate improvement would be to not have the map view reload continuously as it is being resized.

Related stack trace
`
 java.lang.RuntimeException: Waited 5000ms for: <6494c6f7, 21965401>[count 2, qsz 0, owner <AWT-EventQueue-0-FPSAWTAnimator#00-Timer0>] - <AWT-EventQueue-0-Display-.windows_nil-1-EDT-1>
at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
at jogamp.newt.WindowImpl.setVisibleActionImpl(WindowImpl.java:1234)
at jogamp.newt.WindowImpl$VisibleAction.run(WindowImpl.java:1318)
at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:145)
at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
Caused: java.lang.RuntimeException
at jogamp.newt.DefaultEDTUtil.invokeImpl(DefaultEDTUtil.java:252)
at jogamp.newt.DefaultEDTUtil.invoke(DefaultEDTUtil.java:165)
at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:442)
at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2782)
at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1330)
at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1335)
at com.jogamp.newt.opengl.GLWindow.setVisible(GLWindow.java:578)
at com.jogamp.newt.awt.NewtCanvasAWT.detachNewtChild(NewtCanvasAWT.java:1099)
at com.jogamp.newt.awt.NewtCanvasAWT.destroyImpl(NewtCanvasAWT.java:701)
at com.jogamp.newt.awt.NewtCanvasAWT.removeNotify(NewtCanvasAWT.java:660)
at java.awt.Container.remove(Unknown Source)
at java.awt.Container.remove(Unknown Source)
at javax.swing.JViewport.remove(Unknown Source)
at javax.swing.JViewport.setView(Unknown Source)
at javax.swing.JScrollPane.setViewportView(Unknown Source)
at au.gov.asd.tac.constellation.mapview.MapViewTopComponent.lambda$resetContent$37(MapViewTopComponent.java:498)
at java.awt.event.InvocationEvent.dispatch(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Sourc)
at java.awt.EventDispatchThread.run(Unknown Source)`

### Steps to Reproduce

1. Open the Map View
2. Click and drag the Map View pane to resize it horizontally repeatedly 

**Expected behaviour:** The Map View resizes without an error or unnecessary CPU/GPU stress

**Actual behaviour:** The graphics card buffer fills up and causes Constellation to crash

**Reproduces how often:** 100%

**Comment by formalhaut69** [comment]
As a potential solution, I have added a mouseListener to wait for the user to release their mouse before the Map View resizes. I seem to be getting a class not found exception from my code at the moment but does this sound like a solution to the issue?
![image](https://user-images.githubusercontent.com/58677762/71950341-c3012680-3226-11ea-8068-8e0e1b5aee53.png)

**Comment by aldebaran30701** [comment]
The Event handlers would be overridden by the ones within the pane controlling the map view possibly. This is located in this file, and following methods.  https://github.com/constellation-app/constellation/blob/c968184e866a76049d50df69b27b6304f7b739b5/CoreMapView/src/au/gov/asd/tac/constellation/views/mapview/MapViewTileRenderer.java#L410-L412
Maybe a solution exists to access the border of the resized topController somehow and add your mouse handler and refresh logic to that.

**Comment by arcturus2** [comment]
>I seem to be getting a NoClassDefFoundError when it runs at the moment but does this sound like a solution to the issue?

@formalhaut69 What is the NoClassDefFoundError error your getting? Your solution seems like it should work

>The Event handlers would be overridden by the ones within the pane controlling the map view possibly.

@aldebaran30701 I could be wrong because I haven't debugged this myself but looking at the code, changes made to `mouseMoved()` should not be impacted by adding a mouse listener to the `TopComponent`.

**Comment by formalhaut69** [comment]
@arcturus2 I've changed the logic of my solution and I no longer get that error but strangely enough, I can't seem to get the mouseReleased event to trigger. @aldebaran30701 I don't think its getting overridden by the MapViewTileRenderer, I commented out the mouseReleased method from that class and ran my code and it still didn't trigger. My mouseReleased method is also in a separate anonymous class so it shouldn't be getting overridden. 
```java
addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(final ComponentEvent event) {
                event.getComponent().addMouseListener(new MouseAdapter(){
                    @Override
                    public void mouseReleased(MouseEvent e){
                    resetContent();
                    }
                });
                if (event.getComponent().getWidth() != cachedWidth
                        || event.getComponent().getHeight() != cachedHeight) {
                    cachedWidth = event.getComponent().getWidth();
                    cachedHeight = event.getComponent().getHeight();
                }
            }
        });
```

**Comment by formalhaut69** [comment]
@aldebaran30701 and I have been able to implement a delay of half a second so the map now refreshes at an acceptable rate. This does make it much more difficult to fill up the graphics buffer and cause a crash but it can still occur. So it appears to be only a partial solution and doesn't solve the underlying problem. I think what the underlying issue is that the graphics buffer isn't being cleared properly. This is just a guess because I don't know how the buffer works but I'm assuming that it's supposed to be filled up with tasks to complete. What seems to be occurring though, is that the tasks are being completed because the map view is being refreshed and so this leads me to believe that the buffer isn't being emptied correctly. @arcturus2 Do you think that this is the case? And if so, how could I potentially access the graphics buffer to clear it? I'll make a pull request so you can take a look at it. 
```java
// top component resize listener
        addComponentListener(new ComponentAdapter() {
            ScheduledExecutorService scheduledExecutorService =
                Executors.newScheduledThreadPool(1);
            ScheduledFuture scheduledFuture;
            @Override
            //Cancels the previous resize (future) and then performs the latest one every half second 
            public void componentResized(ComponentEvent event) {
                if(scheduledFuture != null) {
                    scheduledFuture.cancel(true);
                }
                scheduledFuture = scheduledExecutorService.schedule(() -> {
                    if (event.getComponent().getWidth() != cachedWidth
                            || event.getComponent().getHeight() != cachedHeight) {
                        cachedWidth = event.getComponent().getWidth();
                        cachedHeight = event.getComponent().getHeight();
                        resetContent();
                    }
                    return null;
                }, 500, TimeUnit.MILLISECONDS);
            }
        });
```

**Comment by arcturus2** [comment]
>@arcturus2 Do you think that this is the case?

@formalhaut69 great work persisting and debugging this. I'd agree that I think it is that the buffers are written to without clearing, causing it to overflow.

>And if so, how could I potentially access the graphics buffer to clear it?

Not sure. The Map view is OpenGL bases as you've found however it uses a different implementation to the graph. The Map view uses [Unfolding Maps](https://github.com/tillnagel/unfolding) which uses an OpenGL library called [Processing](https://github.com/processing/processing/tree/3.3.7.x).

Can you have a look at https://processing.org/reference/clear_.html and see if you can get access to the `PGraphics` object. There might be a call to do this from the Unfolding map classes and @cygnus-x-1 is the best person to help with that.

>I'll make a pull request so you can take a look at it.

Legend. I've done some testing and it's looking much better.

**Comment by formalhaut69** [comment]
Seems to be a different stack trace from what was originally posted. 
```
com.jogamp.opengl.GLException: GL-Error 0x505 while creating mutable storage for target 0x8892 -> buffer 1 of size 64 with data java.nio.DirectFloatBufferU[pos=0 lim=256 cap=256]
	at jogamp.opengl.GLBufferObjectTracker.createBufferStorage(GLBufferObjectTracker.java:176)
	at jogamp.opengl.gl4.GL4bcImpl.glBufferData(GL4bcImpl.java:40258)
	at processing.opengl.PJOGL.bufferData(PJOGL.java:1149)
	at processing.opengl.PGraphicsOpenGL.updatePolyBuffers(PGraphicsOpenGL.java:1230)
	at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2370)
	at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2314)
	at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:1480)
	at de.fhpotsdam.unfolding.mapdisplay.OpenGLMapDisplay.postDraw(OpenGLMapDisplay.java:114)
	at de.fhpotsdam.unfolding.mapdisplay.Java2DMapDisplay.draw(Java2DMapDisplay.java:406)
	at de.fhpotsdam.unfolding.UnfoldingMap.draw(UnfoldingMap.java:366)
	at au.gov.asd.tac.constellation.views.mapview.MapViewTileRenderer.draw(MapViewTileRenderer.java:376)
	at processing.core.PApplet.handleDraw(PApplet.java:2426)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
[catch] at java.util.TimerThread.run(Timer.java:505)

```
@arcturus2 I was able to get access to the Pgraphics object, it seems to be referenced as 'g' in the dispose() method in the MapViewTileRenderer. The clear() method didn't seem to make a difference unfortunately, neither did the flush() method. According to the javadoc comment for the dispose() method, it seems to be a "work in progress" and it also states that the MapViewTileRenderer isn't being properly garbage collected. I believe that this is why the graphics buffer isn't being cleared properly. @cygnus-x-1 is this still something that is planned to be developed?

**Comment by cygnus-x-1** [comment]
I vaguely remember working on this... I think the issue was that either Unfolding or Processing was creating objects with private references and no matter what we tried we couldn't release them from memory. `MapViewTileRenderer.dispose` was an attempt to clean all this up, but there were certain rogue references remaining that just wouldn't be released. It might be worth taking another look at it, but I remember being pretty stuck at the time.

**Comment by serpens24** [comment]
@arcturus2 I'm interested in your thought regarding merging the current changes into master - noting that ultimately there is an underlying problem with the buffer filling up, the changes made to date will make this much harder to occur. We could then either retask this issue to continue digging into the issue @cygnus-x-1 mentions above, or raise a new one.
It feels to me like its worth making the refresh slightly better now and try and find the ultimate solution in slow time.

**Comment by arcturus2** [comment]
@serpens24 and @formalhaut69 just letting you know I merged the changes 6 days ago into master.

Given this solves the immediate issue I'm happy to close this and work on the ultimate solution slow time.
