### ISSUE TITLE
Find causing a null pointer error

### ISSUE THREAD

**Issue by canis-majoris-42** [constellation-app/constellation#324]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Constellation is throwing a NullPointerException from the Find View: au.gov.asd.tac.constellation.find.advanced.FindRule.getFloatFirstArg(FindRule.java:398)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** Find doesn't throw a null pointer exception

**Actual behaviour:** Find throws a null pointer exception

**Reproduces how often:** 100%

### Additional Information

N/A

**Comment by serpens24** [comment]
Even before I get to the exception listed above I get an exeption loading the find pane ...
An extract is shown below:

```
java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at au.gov.asd.tac.constellation.graph.utilities.widgets.DateTimeRangePanel.initComponents(DateTimeRangePanel.java:193)
	at au.gov.asd.tac.constellation.graph.utilities.widgets.DateTimeRangePanel.initialise(DateTimeRangePanel.java:73)
	at au.gov.asd.tac.constellation.graph.utilities.widgets.DateTimeRangePanel.<init>(DateTimeRangePanel.java:63)
	at au.gov.asd.tac.constellation.views.find.gui.FindCriteriaPanel.createCriteriaPanels(FindCriteriaPanel.java:662)
	at au.gov.asd.tac.constellation.views.find.gui.FindCriteriaPanel.<init>(FindCriteriaPanel.java:112)
	at au.gov.asd.tac.constellation.views.find.gui.FindTopComponent.addFindCriteriaPanel(FindTopComponent.java:207)
	at au.gov.asd.tac.constellation.views.find.gui.FindTopComponent.setDefaultFindCriteriaPanels(FindTopComponent.java:673)
	at au.gov.asd.tac.constellation.views.find.gui.FindTopComponent.restoreState(FindTopComponent.java:272)
	at au.gov.asd.tac.constellation.views.find.gui.FindTopComponent.readStateFromGraph(FindTopComponent.java:747)
	at au.gov.asd.tac.constellation.views.find.gui.FindTopComponent.setNode(FindTopComponent.java:954)
	at au.gov.asd.tac.constellation.views.find.gui.FindTopComponent.resultChanged(FindTopComponent.java:319)
```

The ultimate line in question is shown below:
calendarButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/au/gov/asd/tac/constellation/graph/visual/widgets/resources/calendar.png"))); // NOI18N


Now, I searches the constellation directory structure (at least the github version and the path to /au/gov/asd/tac/constellation/graph/visual/widgets/resources/calendar.png doesn't seem to exist ... perhaps when code was refactored it caused an issue ?

**Comment by serpens24** [comment]
With the above issues addressed, I can get the find panel to display. I then did the follwing:
1. Open a new graph and added a few nodes (using Draw Mode).
2. Ensure nodes are being searched.
3. Selected Advanced Find, and select x as an attribute to search (this should trigger a float search). 
4. ran the find

** I didn't get the exception, however also didnt see the code in question getting triggered ...... is there another way to trigger a float search ?

**Comment by formalhaut69** [comment]
@canis-majoris-42 do you mind adding a bit more detail to this issue describing how you got the exception to occur or did you just simply open the Find view?

**Comment by arcturus2** [comment]
@serpens24  would you be able to upload the fix you have made so far. That will help me out to get a reproducer of the original issue. Thank you.

**Comment by formalhaut69** [comment]
> 
> 
> @serpens24 would you be able to upload the fix you have made so far. That will help me out to get a reproducer of the original issue. Thank you.

@arcturus2 I had the changes on my machine so I've made a pull request with them.

**Comment by arcturus2** [comment]
OK thanks @formalhaut69. I wasn't able to reproduce the original issue anymore either.
