### ISSUE TITLE
New graph button sometimes disappears

### ISSUE THREAD

**Issue by canis-majoris-42** [constellation-app/constellation#327]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

This happens randomly. I think it is a race condition type of issue which should be investigated and fixed.

 {code}
INFO [org.openide.loaders.FolderInstance.Toolbars]: Cannot create org.openide.loaders.FolderInstance$HoldInstance@276bd96d[Toolbars/File]
java.io.IOException: Cyclic reference. Somebody is trying to get value from FolderInstance (org.openide.awt.Toolbar$Folder) from the same thread that is processing the instance
    at org.openide.loaders.FolderInstance.instanceCreate(FolderInstance.java:299)
    at org.openide.loaders.FolderInstance.instanceForCookie(FolderInstance.java:580)
    at org.openide.loaders.FolderInstance$HoldInstance.instanceCreate(FolderInstance.java:1153)
[catch] at org.openide.loaders.FolderInstance$1R.instances(FolderInstance.java:700)
    at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:721)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
{code} 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** New Graph Button never disappears

**Actual behaviour:** New Graph Button sometimes disappears

**Reproduces how often:** Sometimes

### Additional Information

N/A

**Comment by canis-majoris-42** [comment]
Duplicate
