### ISSUE TITLE
Error rendering a lot of blazes

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#405]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

With a lot of blazes on a graph if you try to zoom in and out, it eventually causes a graphics card error and you can't interact with the graph anymore.
 
```java
java.lang.NullPointerException
    at au.gov.asd.tac.constellation.graph.StoreGraph.getObjectValue(StoreGraph.java:1772)
    at au.gov.asd.tac.constellation.visualgraph.display.GraphVisualAccess.getBlazed(GraphVisualAccess.java:920)
    at au.gov.asd.tac.constellation.display.renderer.batcher.BlazeBatcher.bufferBlaze(BlazeBatcher.java:147)
    at au.gov.asd.tac.constellation.display.renderer.batcher.BlazeBatcher.fillBatch(BlazeBatcher.java:140)
    at au.gov.asd.tac.constellation.display.renderer.batcher.BlazeBatcher.updateBlazes(BlazeBatcher.java:105)
    at au.gov.asd.tac.constellation.display.renderer.GraphRenderable.lambda$getChangeProcessor$21(GraphRenderable.java:255)
    at au.gov.asd.tac.constellation.visualsupport.display.VisualProcessor.lambda$null$1(VisualProcessor.java:289)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at au.gov.asd.tac.constellation.visualsupport.display.VisualProcessor.lambda$processChangeSet$2(VisualProcessor.java:288)
    at java.util.HashMap.forEach(HashMap.java:1288)
    at au.gov.asd.tac.constellation.visualsupport.display.VisualProcessor.processChangeSet(VisualProcessor.java:286)
    at au.gov.asd.tac.constellation.visualsupport.display.VisualProcessor.lambda$update$0(VisualProcessor.java:200)
[catch] at java.lang.Thread.run(Thread.java:748)
```

There was a GL error around the same time which was
GLReadBufferUtil.readPixels: readPixels error 0x502 1038x633

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Auriga2** [comment]
I cannot recreate this in a graph with (up to) 100000 nodes and 50000 transactions. Added blazes on every node.
No errors are thrown when zooming in and out.

**Comment by arcturus2** [comment]
That's a decent test @Auriga2. Perhaps can you try pushing the nodes to 1 million and not bother with creating any transactions (given you can't blaze them) and try creating another graph and then try swapping tabs back and forth several times quickly.

Assuming you are on Windows, can you install https://www.cockos.com/licecap and gif it, only if its not too much trouble? I think it would be cool to see 😄 

I'd say based on this test,if you can't reproduce it then I'd be happy to close it as can't reproduce.

**Comment by Auriga2** [comment]
Had trouble creating a graph with 1M nodes. Same with 500K. 
It's just spinning with high memory and CPU usage. No graph is drawn for 30+ minutes, and no errors were thrown. (Same when running from the binary as well as under development)

And I got this error when I added another graph with 100K nodes, while waiting for the above graph to load. (only in development) 
```
java.lang.ArrayIndexOutOfBoundsException: Index 4100 out of bounds for length 4096
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphRectangleBuffer.addRectImage(GlyphRectangleBuffer.java:224)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI.lambda$renderTextAsLigatures$5(GlyphManagerBI.java:421)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI.renderTextAsLigatures(GlyphManagerBI.java:415)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.bufferTopLabel(NodeLabelBatcher.java:243)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.fillTopLabels(NodeLabelBatcher.java:204)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.createBatch(NodeLabelBatcher.java:157)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.lambda$getChangeProcessor$3(GraphRenderable.java:160)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$processChangeSet$1(VisualProcessor.java:296)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$processChangeSet$2(VisualProcessor.java:295)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.processChangeSet(VisualProcessor.java:293)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$update$0(VisualProcessor.java:206)
[catch] at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by Auriga2** [comment]
Finally, it loaded. (In 44 minutes, with additional views closed) But couldn't recreate the original error, although working with this graph is super slow. Attached a gif. 

![1MblazesZoom](https://user-images.githubusercontent.com/64826928/82004103-3ae1d080-96a1-11ea-96d5-2491d3e6cc58.gif)

Swapping tabs make the constellation to go "Not Responding", if the other graphs are also big. With smaller other graphs, no problem.

**Comment by arcturus2** [comment]
Oh wow. Thank you gifting it and for the patience. I should have asked what the spec of your computer was....

Most of the delay will be with the graphs card trying to render the graph Constellation built.

So I think it is safe to say this issue is no longer a problem!

Thank you for your patience with testing this graph @Auriga2.
