### ISSUE TITLE
Testing Constellation 2.0.0-rc1

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#411]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Make a version of Constellation using NetBeans 11.3 and Java 11 available for analyst to test. See https://github.com/constellation-app/constellation/issues?q=is%3Aissue+is%3Aopen+label%3Av2.0.0-beta for a list of outstanding issues.

**Comment by arcturus2** [comment]
I'm getting the following error when running a `build-jre-zip`

```java
java.lang.ClassNotFoundException: javax.help.HelpSet starting from ModuleCL@1b94a999[org.netbeans.modules.javahelp] with possible defining loaders [ModuleCL@1b94a999[org.netbeans.modules.javahelp]] and declared parents [ModuleCL@4714699e[org.netbeans.api.progress], ModuleCL@21826e89[org.openide.awt], org.netbeans.MainImpl$BootClassLoader@3dd3bcd, ModuleCL@76dff13a[org.openide.loaders], ModuleCL@226db051[org.openide.nodes], ModuleCL@4651651b[org.openide.windows], ModuleCL@248e4539[org.netbeans.spi.quicksearch], org.netbeans.JarClassLoader@1cc1d000, ModuleCL@1cbe6110[org.netbeans.api.progress.nb]]
    at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:215)
    at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
Caused: java.lang.NoClassDefFoundError: javax/help/HelpSet
    at org.netbeans.modules.javahelp.HelpSetProcessor$1.instanceClass(HelpSetProcessor.java:88)
    at org.openide.loaders.XMLDataObject$ICDel.instanceClass(XMLDataObject.java:1366)
    at org.openide.loaders.XMLDataObject$ICDel.instanceOf(XMLDataObject.java:1379)
    at org.openide.loaders.FolderLookup.instanceForCookie(FolderLookup.java:190)
    at org.openide.loaders.FolderInstance$HoldInstance.instanceCreate(FolderInstance.java:1132)
    at org.openide.loaders.FolderLookup.createInstance(FolderLookup.java:141)
    at org.openide.loaders.FolderInstance.defaultProcessObjectsFinal(FolderInstance.java:863)
    at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:705)
    at org.openide.loaders.FolderLookup.postCreationTask(FolderLookup.java:235)
    at org.openide.loaders.FolderInstance.processObjects(FolderInstance.java:745)
    at org.openide.loaders.FolderInstance$Listener.finished(FolderInstance.java:1034)
    at org.openide.loaders.FolderList.createBoth(FolderList.java:854)
    at org.openide.loaders.FolderList.getObjects(FolderList.java:539)
    at org.openide.loaders.FolderList.access$600(FolderList.java:52)
    at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:938)
    at org.openide.loaders.FolderList$ListTask.run(FolderList.java:914)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
    at org.openide.util.RequestProcessor$Processor.doEvaluate(RequestProcessor.java:2086)
    at org.openide.util.RequestProcessor$Task.waitFinished(RequestProcessor.java:1650)
    at org.openide.loaders.FolderInstance.waitFinished(FolderInstance.java:307)
    at org.openide.loaders.FolderInstance.instanceCreate(FolderInstance.java:256)
    at org.openide.loaders.FolderLookup.instanceForCookie(FolderLookup.java:197)
    at org.openide.loaders.FolderInstance$HoldInstance.instanceCreate(FolderInstance.java:1132)
    at org.openide.loaders.FolderLookup.createInstance(FolderLookup.java:141)
    at org.openide.loaders.FolderInstance.defaultProcessObjectsFinal(FolderInstance.java:863)
    at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:705)
    at org.openide.loaders.FolderLookup.postCreationTask(FolderLookup.java:235)
    at org.openide.loaders.FolderInstance.processObjects(FolderInstance.java:745)
    at org.openide.loaders.FolderInstance$Listener.finished(FolderInstance.java:1034)
    at org.openide.loaders.FolderList.createBoth(FolderList.java:854)
    at org.openide.loaders.FolderList.getObjects(FolderList.java:539)
    at org.openide.loaders.FolderList.access$600(FolderList.java:52)
    at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:938)
    at org.openide.loaders.FolderList$ListTask.run(FolderList.java:914)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by aldebaran30701** [comment]
To keep up to date witch which sections have been tested:
I've tested the **Analytic View** for functionality of menus, running of plugins and a brief UX overview.
#455 #456

**Comment by aldebaran30701** [comment]
This ticket has been since renamed. 
https://github.com/constellation-app/constellation/releases/tag/v2.0.0-beta2
Testing can still follow on from the previous beta to further improve the application.

**Comment by arcturus2** [comment]
We are now up to beta4. Expect another beta soon which a number of PRs which are almost over the line and some already merged in today.

**Comment by arcturus2** [comment]
Closing this and will continue in #667
