### ISSUE TITLE
NoClassDefFoundError at startup

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#542]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The following `java.lang.NoClassDefFoundError` error shows up when running Constellation. This has been observed for several weeks. It doesn't look like its affecting the functionality but I don't want to take my chances.

```java
Caught and handled this exception :
java.lang.NoClassDefFoundError: com/sun/media/imageioimpl/common/BogusColorSpace
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReaderSpi.onRegistration(TIFFImageReaderSpi.java:170)
	at java.desktop/javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:765)
	at java.desktop/javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:307)
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:189)
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:113)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:134)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at org.openide.util.ImageUtilities.<clinit>(ImageUtilities.java:141)
	at org.netbeans.core.startup.Splash.loadContentIcon(Splash.java:248)
	at org.netbeans.core.startup.Splash.access$400(Splash.java:50)
	at org.netbeans.core.startup.Splash$SplashPainter.init(Splash.java:477)
	at org.netbeans.core.startup.Splash$SplashPainter$1.run(Splash.java:518)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.sun.media.imageioimpl.common.BogusColorSpace starting from ModuleCL@6f347a02[au.gov.asd.tac.constellation.dependencies] with possible defining loaders null and declared parents ]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more
Caused by: java.lang.ClassNotFoundException: com.sun.media.imageioimpl.common.BogusColorSpace
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
	... 27 more
Caught and handled this exception :
java.lang.NoClassDefFoundError: com/sun/media/imageioimpl/common/BogusColorSpace
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageWriterSpi.onRegistration(TIFFImageWriterSpi.java:147)
	at java.desktop/javax.imageio.spi.SubRegistry.registerServiceProvider(ServiceRegistry.java:765)
	at java.desktop/javax.imageio.spi.ServiceRegistry.registerServiceProvider(ServiceRegistry.java:307)
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:189)
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:113)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:134)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at org.openide.util.ImageUtilities.<clinit>(ImageUtilities.java:141)
	at org.netbeans.core.startup.Splash.loadContentIcon(Splash.java:248)
	at org.netbeans.core.startup.Splash.access$400(Splash.java:50)
	at org.netbeans.core.startup.Splash$SplashPainter.init(Splash.java:477)
	at org.netbeans.core.startup.Splash$SplashPainter$1.run(Splash.java:518)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.sun.media.imageioimpl.common.BogusColorSpace starting from ModuleCL@6f347a02[au.gov.asd.tac.constellation.dependencies] with possible defining loaders null and declared parents ]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more
Caused by: java.lang.ClassNotFoundException: com.sun.media.imageioimpl.common.BogusColorSpace
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
	... 27 more
```
### Steps to Reproduce

1. Start Constellation
2. Help -> Show Logs

**Expected behaviour:** There shouldn't be any exceptions at startup

**Actual behaviour:** There is an error in the log file which is caught by NetBeans so there is no pop-up but the error is there

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by aldebaran30701** [comment]
Just to let you know, I'm running from current master and the .exe for the beta release and this does not yield me any errors in the logs at startup for either.

**Comment by arcturus2** [comment]
Hmm interesting. Honestly I actually saw it when running Constellation from NetBeans. Are you able to test it from there and confirm?

**Comment by aldebaran30701** [comment]
My previous comment didn't read as good as it sounded in my head - I tested it on both the run through Netbeans, and also the .exe.

**Comment by arcturus2** [comment]
Thanks @aldebaran30701 for the clarification. I'm happy for it to be an issue only on my setup. I'll keep this open a little longer to see if I find out why I'm getting it and the close asap.

**Comment by cygnus-x-1** [comment]
I also don't see this for both cases.
