### ISSUE TITLE
Reduce/Remove lag when a graph has to redraw due to windowing changes

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#59]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/faq
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/repositories-catalog

### Description

When a large graph is open and views/other tabs are opened/closed, it triggers a redraw of the large graph. This seems to cause considerable lag, which the funny visual side-effect of the graph canvas being blank until the graph is redrawn.

It may not be possible to truly solve this in a nice manner, but perhaps we could reduce the jarring effect of the graph seeming to disappear for a few seconds.

### Steps to Reproduce

1. Open a graph
2. Select All
3. Ctrl + U
4. Click on the previous graph
5. Click on the new graph

**Expected behaviour:** The new graph should render

**Actual behaviour:** The graph is blank and it either takes a few seconds to render or by zooming in and out

**Reproduces how often:** 100%

### Additional Information

The new renderer framework has been made to be very efficient as to when it should renderer and perhaps some of the logic is too strong, preventing the graphics card from being informed that there is a graph that needs to be displayed.

**Comment by aldebaran30701** [comment]
I had an exception occur similar to the steps of this issue. Let me know if you want it in a new ticket. I have only been able to replicate it once, with sphere graph builder and 10000 nodes + transactions + all displayable chars.
`
au.gov.asd.tac.constellation.visual.opengl.utilities.RenderException: Incorrect amount of data for the specified target [size=851484, limit=10, position=0]
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.Batch.bufferData(Batch.java:365)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.Batch.buffer(Batch.java:334)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.lambda$createBatch$0(NodeLabelBatcher.java:163)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.lambda$update$29(GraphRenderable.java:376)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.update(GraphRenderable.java:375)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.lambda$display$2(GLRenderer.java:164)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.display(GLRenderer.java:163)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1424)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
Caused: com.jogamp.opengl.GLException: Caught RenderException: Incorrect amount of data for the specified target [size=851484, limit=10, position=0] on thread AWT-EventQueue-1
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1438)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused: java.lang.RuntimeException
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:201)
	at com.jogamp.opengl.Threading.invokeOnOpenGLThread(Threading.java:202)
	at com.jogamp.opengl.Threading.invoke(Threading.java:221)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:505)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLVisualProcessor.performVisualUpdate(GLVisualProcessor.java:196)
	at au.gov.asd.tac.constellation.visual.display.VisualProcessor.lambda$update$0(VisualProcessor.java:211)
[catch] at java.lang.Thread.run(Thread.java:748)
`
[JOGL Version.txt](https://github.com/constellation-app/constellation/files/4151239/JOGL.Version.txt)

**Comment by GammaVel** [comment]
I have noticed the same issue with version 2.3.  There is about a one second delay before the graph loads, the screen stays blank. This is after you go back to the original graph and then click on the new graph (same steps as in the issue description). 

This is still an issue. I don't get the exception that @aldebaran30701 mentioned in the first comment.

**Comment by aldebaran30701** [comment]
Adding this here https://github.com/constellation-app/constellation/wiki/Known-Issues
As the issue isn't directly something with this code.
