### ISSUE TITLE
Analytic View Null Pointer

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#628]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

I opened the analytic view and the following null pointer exception occurred:

```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.analyticview.AnalyticConfigurationPane.lambda$updateSelectablePluginsParameters$29(AnalyticConfigurationPane.java:534)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at au.gov.asd.tac.constellation.views.analyticview.AnalyticConfigurationPane.updateSelectablePluginsParameters(AnalyticConfigurationPane.java:530)
	at au.gov.asd.tac.constellation.views.analyticview.AnalyticConfigurationPane.setPluginsFromSelectedQuestion(AnalyticConfigurationPane.java:515)
	at au.gov.asd.tac.constellation.views.analyticview.AnalyticConfigurationPane.lambda$new$13(AnalyticConfigurationPane.java:209)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

1. Open a new graph
2. Open the analytic view

**Expected behaviour:** The view should open without any errors

**Actual behaviour:** A popup with a null pointer error was displaued

**Reproduces how often:** 10%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by formalhaut69** [comment]
@antares1470 this seems similar to the issue that you resolved a while back; https://github.com/constellation-app/constellation/pull/529 just wondering if you'd know any further what could be causing this one.

**Comment by antares1470** [comment]
The issue with the previous one was a race condition between 2 threads editing the same variable. One of the threads had locks applied but the other did not (rendering the locks the first one had useless in this scenario). I suspect that something similar is happening here (in fact there are a lot of similarities in the stack trace here with the one of the issue I worked on #456).

**Comment by aldebaran30701** [comment]
I've just replicated this in the release candidate from opening the Analytic View

**Comment by Nova-2119** [comment]
I have a graph that produces this error every time I open it. Weirdly it still displays and does everything fine afterwards.
