### ISSUE TITLE
Null pointer in Attribute Calculator

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#640]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Running the calculator with the following preferences enabled results in a null pointer error when trying to import modules.

![image](https://user-images.githubusercontent.com/58677759/86866917-09213f00-c111-11ea-8cbe-19d0b95102f3.png)

```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.attributecalculator.plugins.AttributeCalculatorPlugin.importModules(AttributeCalculatorPlugin.java:116)
	at au.gov.asd.tac.constellation.views.attributecalculator.plugins.AttributeCalculatorPlugin.edit(AttributeCalculatorPlugin.java:149)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.describedEdit(SimpleEditPlugin.java:207)
[catch] at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:115)
Caused: java.lang.RuntimeException
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:135)
[catch] at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:122)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

1. new graph
2. open attribute calculator
3. select graph properties
4. select node count
5. select run

**Expected behaviour:** no exception, and correct execution

**Actual behaviour:** exception - null ptr

**Reproduces how often:** 100%

**Comment by arcturus2** [comment]
We are going to delete the Attribute Calculator in #705
