### ISSUE TITLE
Plugin Reporter View Issues

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#644]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

The plugin reporter filter does not seem to change the visible plugin reports on the view. They can be selected and deselected but nothing changes on the view. 

The plugin reporter filter for ignored events does not change the report entries.

The help icon does not link to anything 

### Steps to Reproduce

1. open new graph
2. sphere graph builder
3. select in box plugin (right click and drag)
4. Open plugin reporter

**Expected behaviour:** filters to work, help to operate

**Actual behaviour:** filters don't work, help not operational

**Reproduces how often:** 100%

**Comment by aldebaran30701** [comment]
Experimental -> Developer -> throw a plugin Exception 
This with the plugin reporter opened will result in the following null pointer - possibly leading to more issues with the view.

```
java.lang.NullPointerException
	at impl.org.controlsfx.skin.CheckComboBoxSkin.lambda$new$0(CheckComboBoxSkin.java:106)
[catch] at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.graphics/javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:8148)
	at javafx.graphics/javafx.scene.Node.setFocused(Node.java:8201)
	at javafx.controls/javafx.scene.control.ListCell.updateFocus(ListCell.java:534)
	at javafx.controls/javafx.scene.control.ListCell.lambda$new$3(ListCell.java:201)
	at javafx.base/javafx.beans.WeakInvalidationListener.invalidated(WeakInvalidationListener.java:83)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:72)
	at javafx.base/javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
	at javafx.base/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:114)
	at javafx.base/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls/javafx.scene.control.FocusModel.setFocusedIndex(FocusModel.java:74)
	at javafx.controls/javafx.scene.control.FocusModel.focus(FocusModel.java:147)
	at javafx.controls/javafx.scene.control.ListView$ListViewFocusModel.updateDefaultFocus(ListView.java:1676)
	at javafx.controls/javafx.scene.control.ListView$ListViewFocusModel.lambda$new$1(ListView.java:1604)
	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at au.gov.asd.tac.constellation.views.pluginreporter.panes.PluginReporterPane.updateTags(PluginReporterPane.java:264)
	at au.gov.asd.tac.constellation.views.pluginreporter.panes.PluginReporterPane.lambda$updateReports$5(PluginReporterPane.java:250)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by aldebaran30701** [comment]
The help icon still does not work and can be rolled into one issue that addresses all help icons not working when one is made.
