### ISSUE TITLE
JFX UnsatisfiedLinkError - Jars may not be compatible

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#676]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Testing of rc1 revealed that an error was logged. I did not get the chance to figure out when it happened, but here is the exception. I had two graphs opened, one with a default sphere graph built, and was playing around with the analytic view? 

```
java.lang.UnsatisfiedLinkError: 'boolean com.sun.javafx.font.directwrite.OS.CoInitializeEx(int)'
at javafx.graphics/com.sun.javafx.font.directwrite.OS.CoInitializeEx(Native Method)
at javafx.graphics/com.sun.javafx.font.directwrite.DWFactory.getWICFactory(Unknown Source)
at javafx.graphics/com.sun.javafx.font.directwrite.DWGlyph.createBitmap(Unknown Source)
at javafx.graphics/com.sun.javafx.font.directwrite.DWGlyph.getCachedBitmap(Unknown Source)
at javafx.graphics/com.sun.javafx.font.directwrite.DWGlyph.getD2DMask(Unknown Source)
at javafx.graphics/com.sun.javafx.font.directwrite.DWGlyph.getPixelData(Unknown Source)
at javafx.graphics/com.sun.prism.impl.GlyphCache.getCachedGlyph(Unknown Source)
at javafx.graphics/com.sun.prism.impl.GlyphCache.render(Unknown Source)
at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.drawString(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGText.renderText(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGText.renderContent2D(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGShape.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderForClip(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderRectClip(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderClip(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.renderNodeToCache(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.CacheFilter.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.renderCached(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegi...
```

@arcturus2 - _I noticed an issue with the latest jre from Azul for MacOSX so perhaps we can try winding back the Java version from the 11.0.7 to 11.0.6 and see. Are you able to create a ticket for this_

### Steps to Reproduce

I didn't manage to replicate this again, but can vouch that others have had this same issue logged with rc1.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcturus2** [comment]
Let me know if this can be reproduced in v2.0.0-rc2

**Comment by aldebaran30701** [comment]
Thus far have not found any clue to this being in this V2.0 rc2 👍
