### ISSUE TITLE
JOGL Error when opening table view or timeline view

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#677]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
The following exception occurs when you have one graph with a sphere graph built, and open the table view.
Possibly a resize issue with views.
```
com.jogamp.opengl.GLException: Thread[AWT-EventQueue-0,6,main] glGetError() returned the following error codes after a call to glBindTexture(<int> 0x8C2A, <int> 0xFFFFFFFF): GL_INVALID_OPERATION ( 1282 0x502), 
	at com.jogamp.opengl.DebugGL4bc.writeGLError(DebugGL4bc.java:31781)
	at com.jogamp.opengl.DebugGL4bc.glBindTexture(DebugGL4bc.java:730)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.display(GraphRenderable.java:480)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.lambda$display$3(GLRenderer.java:170)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.display(GLRenderer.java:169)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1428)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
Caused: com.jogamp.opengl.GLException: Caught GLException: Thread[AWT-EventQueue-0,6,main] glGetError() returned the following error codes after a call to glBindTexture(<int> 0x8C2A, <int> 0xFFFFFFFF): GL_INVALID_OPERATION ( 1282 0x502),  on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1442)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:503)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:557)
	at java.desktop/sun.awt.RepaintArea.paintComponent(Unknown Source)
	at java.desktop/sun.awt.RepaintArea.paint(Unknown Source)
	at java.desktop/sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

### Steps to Reproduce

1. new graph
2. build sphere graph
3. open table view

**Expected behaviour:** no exception

**Actual behaviour:** exception and possibly render issues?

**Reproduces how often:** 100%

### Additional Information

was reproduced in v2.0 rc2

**Comment by aldebaran30701** [comment]
Tested in timeline view and it also throws this error. Just confirming it is with the graph specifically and not the table view.

**Comment by aldebaran30701** [comment]
Commenting here to add that this is still currently present as at V2.1 release. 
Recreated with:
New graph -> sphere graph builder -> open analytic view.
(Updated stack trace below)
```
com.jogamp.opengl.GLException: Thread[AWT-EventQueue-0,6,main] glGetError() returned the following error codes after a call to glBindTexture(<int> 0x8C2A, <int> 0xFFFFFFFF): GL_INVALID_OPERATION ( 1282 0x502), 
	at com.jogamp.opengl.DebugGL4bc.writeGLError(DebugGL4bc.java:31781)
	at com.jogamp.opengl.DebugGL4bc.glBindTexture(DebugGL4bc.java:730)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.display(GraphRenderable.java:448)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.lambda$display$3(GLRenderer.java:170)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.display(GLRenderer.java:169)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1428)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
Caused: com.jogamp.opengl.GLException: Caught GLException: Thread[AWT-EventQueue-0,6,main] glGetError() returned the following error codes after a call to glBindTexture(<int> 0x8C2A, <int> 0xFFFFFFFF): GL_INVALID_OPERATION ( 1282 0x502),  on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1442)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:503)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:557)
	at java.desktop/sun.awt.RepaintArea.paintComponent(Unknown Source)
	at java.desktop/sun.awt.RepaintArea.paint(Unknown Source)
	at java.desktop/sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by antares1470** [comment]
@aldebaran30701 is this still an issue? I've just given this a quick test with the reproducers you had mentioned but haven't been able to replicate

**Comment by aldebaran30701** [comment]
@antares1470 I'll give it a test now, but I'm fairly sure this error was only really seen in the executable releases of Constellation.

**Comment by aldebaran30701** [comment]
Confirmed it still occurs in the most recent release https://github.com/constellation-app/constellation/releases/tag/v2.1.1

**Comment by aldebaran30701** [comment]
Confirmed still an issue in most recent release candidate https://github.com/constellation-app/constellation/releases/tag/v2.3.0-rc1

**Comment by GammaVel** [comment]
I retested this bug and I am unable to reproduce it. I tried both the sphere graph build and the small world graph with the Table view and Analytic view. I have checked the Output logs and the plugin reporter and there are no errors shown.  Based on successful retesting this can be closed.
