### ISSUE TITLE
ClassNotFoundException in rc2 - Attribute Calculator

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#682]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description
One graph opened with sphere graph built,
Open attribute calculator

```
INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'AttributeCalculatorTopComponent'. Reason: java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.views.scripting.calculator.AttributeCalculatorTopComponent starting from SystemClassLoader[109 modules] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@3dd3bcd, org.netbeans.JarClassLoader@382c13e5, ModuleCL@7b0416c7[org.netbeans.api.annotations.common], ModuleCL@484cffd2[org.openide.awt], ModuleCL@60ae8294[org.netbeans.api.progress], ModuleCL@222d1baf[org.netbeans.api.progress.nb], ModuleCL@79c48303[org.openide.dialogs], ModuleCL@56595186[org.openide.nodes], ModuleCL@42f7c3fb[org.openide.windows], ModuleCL@84d5869[org.netbeans.modules.editor.mimelookup], ...92 more]
java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.views.scripting.calculator.AttributeCalculatorTopComponent
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.views.scripting.calculator.AttributeCalculatorTopComponent starting from SystemClassLoader[109 modules] with possible defining loaders null and declared parents [org.netbeans.MainImpl$BootClassLoader@3dd3bcd, org.netbeans.JarClassLoader@382c13e5, ModuleCL@7b0416c7[org.netbeans.api.annotations.common], ModuleCL@484cffd2[org.openide.awt], ModuleCL@60ae8294[org.netbeans.api.progress], ModuleCL@222d1baf[org.netbeans.api.progress.nb], ModuleCL@79c48303[org.openide.dialogs], ModuleCL@56595186[org.openide.nodes], ModuleCL@42f7c3fb[org.openide.windows], ModuleCL@84d5869[org.netbeans.modules.editor.mimelookup], ...92 more]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at org.netbeans.ModuleManager$SystemClassLoader.loadClass(ModuleManager.java:769)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.openide.windows.TopComponent$Replacer.readObject(TopComponent.java:1821)
Caused: java.io.IOException
	at org.openide.windows.TopComponent$Replacer.readObject(TopComponent.java:1881)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject(Unknown Source)
	at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.readSerial(XMLSettingsSupport.java:546)
	at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.instanceCreate(XMLSettingsSupport.java:578)
	at org.netbeans.modules.settings.convertors.SerialDataConvertor$SettingsInstance.instanceCreate(SerialDataConvertor.java:401)
[catch] at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:547)
	at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:657)
	at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:453)
	at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:1002)
	at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:270)
	at org.openide.windows.OpenComponentAction.getTopComponent(OpenComponentAction.java:53)
	at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:66)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:174)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:70)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:91)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:74)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:177)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Reproduces how often:** 100%

### Additional Information

tested on v2.0 rc2

**Comment by aldebaran30701** [comment]
Closing this as Attribute calculator may not be further supported
