### ISSUE TITLE
New Graph - Concurrent Mod with DAV Opened

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#707]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Opening a new graph while the Data Access View is opened will cause an exception as below:

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at au.gov.asd.tac.constellation.graph.node.plugins.FrameworkGraphManager.graphOpened(FrameworkGraphManager.java:102)
	at au.gov.asd.tac.constellation.graph.node.GraphNode.<init>(GraphNode.java:162)
	at au.gov.asd.tac.constellation.graph.node.GraphNode.<init>(GraphNode.java:135)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphTopComponent.<init>(VisualGraphTopComponent.java:436)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.done(VisualGraphOpener.java:222)
	at java.desktop/javax.swing.SwingWorker$5.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at java.desktop/sun.swing.AccumulativeRunnable.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

### Steps to Reproduce

1. Open Constellation
2. Open DAV
3. Open new graph

**Expected behaviour:** New graph launches without issue

**Actual behaviour:** Exception occurs and graph does not load.

**Reproduces how often:** 100%

### Additional Information

Found through testing .exe release of v2.0 rc2
Only occurs for myself in the .exe versions.

**Comment by aldebaran30701** [comment]
I can't figure out how to debug this effectively. I've done a static analysis of how the code gets triggered and the closest I was able to get was that the listeners triggered on making a new graph are also used concurrently when the DAV is listening. I haven't tracked down what specific listener was causing it as no error on the DAV side of things occurs. Keen to hear people's thoughts on how to tackle this since it is in the executable current release V2.0.0

**Comment by arcturus2** [comment]
@aldebaran30701 I have a couple of thoughts:

1) if you want to be able to interactively debug the app whilst using the v2 executable you can do so by running the exe and then from NetBeans go to Profile -> Attach to External Process

2) One difference between running from the .exe and from NetBeans is the user directory and cache directory. When you run Constellation from NetBeans and click on Help -> About in Constellation you will see that there is a build/testuserdir directory being referenced. Run Constellation from the exe and observe the location it provides, then proceed to copy the user dir and paste it over the top of testuserdir. Now try running Constellation from NetBeans once again (and don't do a clean build because it will wipe the files) and see if you can reproduce it from NetBeans.

Let me know if either option helps and if not we can have another rethink.

**Comment by Nova-2119** [comment]
I just tired this and was unable to replicate the issue

**Comment by aldebaran30701** [comment]
I just tried this in the v2.1.0-rc1 .exe and it still occurs. 
Note that the issue only happens in the executable. @Nova-2119 did you test it in the .exe or the netbeans build?
Here is the error.
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at au.gov.asd.tac.constellation.graph.node.plugins.FrameworkGraphManager.graphOpened(FrameworkGraphManager.java:102)
	at au.gov.asd.tac.constellation.graph.node.GraphNode.<init>(GraphNode.java:162)
	at au.gov.asd.tac.constellation.graph.node.GraphNode.<init>(GraphNode.java:135)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphTopComponent.<init>(VisualGraphTopComponent.java:451)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.done(VisualGraphOpener.java:222)
	at java.desktop/javax.swing.SwingWorker$5.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at java.desktop/sun.swing.AccumulativeRunnable.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by antares1470** [comment]
#949 outlines the actual issue here so leaving that one open and closing this one
