### ISSUE TITLE
Scatter Plot View negative or zero log axis out of memory error

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#720]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Running the view on an empty graph, or sphere graph, while selecting parameters and clicking buttons "selected" and "log scale X" caused it to lock up and throw an out of memory error.
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.Double.valueOf(Double.java:524)
	at au.gov.asd.tac.constellation.views.scatterplot.axis.LogarithmicAxis.calculateTickValues(LogarithmicAxis.java:153)
	at javafx.controls/javafx.scene.chart.Axis.computePrefHeight(Axis.java:582)
	at javafx.graphics/javafx.scene.Parent.prefHeight(Parent.java:1037)
	at javafx.graphics/javafx.scene.layout.Region.prefHeight(Region.java:1559)
	at javafx.controls/javafx.scene.chart.XYChart.layoutChartChildren(XYChart.java:697)
	at javafx.controls/javafx.scene.chart.Chart$1.layoutChildren(Chart.java:95)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.Toolkit$$Lambda$518/0x000000080093f040.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$372/0x000000080073d040.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication$$Lambda$368/0x000000080073e040.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

1. Open new graph
2. Open view
3. Select transaction, visibility, identifier, and click selected, log scale x multiple times. (NOTE: I selected a few different items from within the dropdowns)

**Expected behaviour:** Not freeze up

**Actual behaviour:** freezes

**Reproduces how often:** 100%

### Additional Information
Found during testing of V2.0 rc2

**Comment by formalhaut69** [comment]
@CrucisGamma, I've taken a look at this issue and I've found the cause but I don't know the scatter plot well so I'm not sure what the solution should be. On occasion the scatter plot will load an empty graph when you select identifier and then visibility, when this occurs the user can then select and run Log Scale Y-Axis. The calculateTickValues method will eventually run and within it the logLowerBound will be set to Math.log10(lowerBound) which is negative infinity because the lowerbound is 0. This will cause an infinite loop on line 150 because -infinity is always less than the logUpperBound. During every loop, tickValues are added to an array until the application runs out of memory. I could change it so that if major == -infinity then break but perhaps these buttons shouldn't even be enabled if the scatter plot is empty. What do you think? 

https://github.com/constellation-app/constellation/blob/master/CoreScatterPlotView/src/au/gov/asd/tac/constellation/views/scatterplot/axis/LogarithmicAxis.java#L138-L157 

![image](https://user-images.githubusercontent.com/58677762/88506843-1055b180-d01a-11ea-8afc-082c2eb6a7e5.png)

**Comment by formalhaut69** [comment]
@cygnus-x-1, @antares1470 hey guys, could you have a quick read of my analysis here when you get the chance? Thanks

**Comment by antares1470** [comment]
@formalhaut69 I think you're analysis is correct in that we probably don't want to be in a situation where we are creating an endless amount of ticks on the graph. Disabling the buttons might partially fix the problem but I suspect this might look a little odd from a users perspective (usually we only disable things when they're not applicable). (Also if you've got a log scale already selected for either axes and then change attributes resulting in a blank scatter plot, disabling probably won't avoid the problem)

Another solution might be to limit the number of ticks created when major == -inf, perhaps stopping after a certain number of loop iterations. It presents something but doesn't destroy the memory use and doesn't require disabling anything

**Comment by formalhaut69** [comment]
Got a little bit further with this one and realised that whilst an infinite for loop does occur, it seems that that's not the entire issue. It appears that clicking on the Log scale Y-axis button will cause a crash whenever the scatter plot has content in it.

**Comment by Nova-2119** [comment]
I am unable to reproduce this error currently. I also feel like the scatterplot isn't acting as it should, it doesn't seem to be updating.
@formalhaut69 
@antares1470 
Are either of you able to reproduce the error and/or confirm that the scatterplot is updating as it should?

**Comment by formalhaut69** [comment]
@Nova-2119, yeah, it doesn't always update. I can get it to load content on occasion but neither of the log scale buttons function for me. The Y-Axis always freezes constellation and the X-Axis one will never function.

**Comment by Nova-2119** [comment]
@formalhaut69 there's always a bigger bug.

@arcturus2 I'll start looking into this.

**Comment by Nova-2119** [comment]
Okay so I believe there are two distinct out of memory errors.
The first is triggered by trying to run log axis on values that are <=0.
The second is triggered by trying when you have nothing selected on the graph but try to tell the scatterplot to show only selected nodes with a log axis.

The two will need different solutions so i'm going to split them into two separate issue.
I will rename this one and have it focus on  the first issue.
The second issue can be found here: https://github.com/constellation-app/constellation/issues/815
