### ISSUE TITLE
Exception opening a graph first time

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#729]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Opening a new graph or existing graph for the first time creates a concurrent mod exception. Clicking on open graph again works.

```java
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at au.gov.asd.tac.constellation.graph.node.plugins.FrameworkGraphManager.graphOpened(FrameworkGraphManager.java:102)
	at au.gov.asd.tac.constellation.graph.node.GraphNode.<init>(GraphNode.java:162)
	at au.gov.asd.tac.constellation.graph.node.GraphNode.<init>(GraphNode.java:135)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphTopComponent.<init>(VisualGraphTopComponent.java:436)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.done(VisualGraphOpener.java:222)
	at java.desktop/javax.swing.SwingWorker$5.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at java.desktop/sun.swing.AccumulativeRunnable.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

### Steps to Reproduce

1. Open a graph

**Expected behaviour:** Graph should open

**Actual behaviour:** No graph opens and I am greeted with an exception

**Reproduces how often:** 40%

### Additional Information

The views I had docked are Data Access, Conversation and Attribute Editor. Minimised are Analytic View and Scatter Plot.

**Comment by aldebaran30701** [comment]
Duplicate of #707
