### ISSUE TITLE
Scatterplot view ClassCastException when selecting nodes from the plot.

### ISSUE THREAD

**Issue by Nova-2119** [constellation-app/constellation#793]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Get a ClassCastException when selecting nodes from the plot.

### Steps to Reproduce

1. Open New Graph
2. Build Sphere Graph
3. Open Scatterplot view
4. Select Node, X, Y
5. Close Scatterplot View
6. Open Scatterplot View
7. Select node in Scatterplot.

**Expected behaviour:** [What you expect to happen]
Node should be selected in both the scatterplot view and the normal graph

**Actual behaviour:** [What actually happens]
ClassCastException Error

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

** Related Issues **
#801

**Comment by arcturus2** [comment]
Please see my comment in https://github.com/constellation-app/constellation/pull/781#issuecomment-675911296

**Comment by aldebaran30701** [comment]
Stacktrace:

```
java.lang.ClassCastException: class au.gov.asd.tac.constellation.plugins.parameters.types.ElementTypeParameterValue cannot be cast to class au.gov.asd.tac.constellation.plugins.parameters.types.SingleChoiceParameterType$SingleChoiceParameterValue (au.gov.asd.tac.constellation.plugins.parameters.types.ElementTypeParameterValue and au.gov.asd.tac.constellation.plugins.parameters.types.SingleChoiceParameterType$SingleChoiceParameterValue are in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @5b2b02b)
	at au.gov.asd.tac.constellation.plugins.parameters.types.SingleChoiceParameterType$SingleChoiceParameterValue.setObjectValue(SingleChoiceParameterType.java:455)
	at au.gov.asd.tac.constellation.plugins.parameters.PluginParameter.setObjectValue(PluginParameter.java:477)
	at au.gov.asd.tac.constellation.plugins.parameters.PluginParameters.setObjectValue(PluginParameters.java:699)
	at au.gov.asd.tac.constellation.plugins.PluginExecution.withParameter(PluginExecution.java:204)
	at au.gov.asd.tac.constellation.views.scatterplot.ScatterChartPane.selectElementsOnGraph(ScatterChartPane.java:423)
	at au.gov.asd.tac.constellation.views.scatterplot.ScatterChartPane$1.handle(ScatterChartPane.java:192)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$4(EmbeddedScene.java:286)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$5(EmbeddedScene.java:279)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
