### ISSUE TITLE
ClassCastException in Histogram view

### ISSUE THREAD

**Issue by formalhaut69** [constellation-app/constellation#801]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

When clicking on the "Filter On Selection" button a class cast exception will be thrown.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behaviour:** [What you expect to happen]

**Actual behaviour:** [What actually happens]

**Reproduces how often:** 100%

### Additional Information

java.lang.ClassCastException: class au.gov.asd.tac.constellation.plugins.parameters.types.ElementTypeParameterValue cannot be cast to class au.gov.asd.tac.constellation.plugins.parameters.types.SingleChoiceParameterType$SingleChoiceParameterValue (au.gov.asd.tac.constellation.plugins.parameters.types.ElementTypeParameterValue and au.gov.asd.tac.constellation.plugins.parameters.types.SingleChoiceParameterType$SingleChoiceParameterValue are in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @66274204)
	at au.gov.asd.tac.constellation.plugins.parameters.types.SingleChoiceParameterType$SingleChoiceParameterValue.setObjectValue(SingleChoiceParameterType.java:455)
	at au.gov.asd.tac.constellation.plugins.parameters.PluginParameter.setObjectValue(PluginParameter.java:477)
	at au.gov.asd.tac.constellation.views.histogram.HistogramTopComponent.filterOnSelection(HistogramTopComponent.java:493)
	at au.gov.asd.tac.constellation.views.histogram.HistogramControls.filterSelectionButtonActionPerformed(HistogramControls.java:507)
	at au.gov.asd.tac.constellation.views.histogram.HistogramControls$7.actionPerformed(HistogramControls.java:341)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by formalhaut69** [comment]
It appears as though this is the same issue as this one; https://github.com/constellation-app/constellation/issues/793. It might be okay to close this, pending a second opinion.

**Comment by antares1470** [comment]
> It appears as though this is the same issue as this one; #793. It might be okay to close this, pending a second opinion.

Happy to hold on to this ticket for now but given this and #793 stem from the same problem (the changes to `SingleChoiceParameterValue`), it may be worth consolidating all of these (including any that haven't been identified yet) into one ticket
