### ISSUE TITLE
Aggregation Method Combo Box IndexOutOfBounds Exception

### ISSUE THREAD

**Issue by Delphinus8821** [constellation-app/constellation#891]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

In the Analytic View, when attempting to change the Aggregation Method combo box after making a selection of nodes/transactions on the graph an IndexOutOfBounds Exception is thrown. An Analytic must be chosen from the categories above the combo box for the exception to occur. 

### Steps to Reproduce

1. Open a Sphere Graph and the Analytic View
2. Choose an analytic from the categories list 
3. Make a selection on the graph and attempt to change the aggregation method combo box

**Expected behaviour:** The combo box to update to the new value

**Actual behaviour:** An IndexOutOfBounds Exception is thrown

**Reproduces how often:** 100%

### Additional Information

Example of the bug:

![aggregationLevel2](https://user-images.githubusercontent.com/73083035/98614888-4b6dbd80-2349-11eb-86a5-7adb2c202cf2.gif)

**Comment by aldebaran30701** [comment]
Commenting to mention some info.

Open new graph -> sphere graph build -> open analytic view -> make graph selection (half the graph) -> select an analytic -> select an aggregation method -> click on the graph:
When this occurs it doesnt allow you to view any other analytic parameters. Until you restart the application. 

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableList.get(Unknown Source)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.get(Unknown Source)
	at javafx.controls/javafx.scene.control.ListView$ListViewBitSetSelectionModel.getModelItem(Unknown Source)
	at javafx.controls/javafx.scene.control.MultipleSelectionModelBase.select(Unknown Source)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.layoutChildren(Unknown Source)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.layout(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by Delphinus8821** [comment]
@arcturus2 I did some testing and could not reproduce the issue on version 2.0. In version 2.0, when making a selection of transactions on a graph the aggregation combo box would reset to displaying as empty but the rest of the functionality still worked and a value was able to be reselected. @Polaris5514 was looking into this issue for a while with the now fixed issue #842, so this issue has been present for ~2 months.

**Comment by Nova-2119** [comment]
Okay so I think I found out whats causing this....at the very least i've made a quick fix which seems to work.

I believe that whenever a parameter on the graph is changes the analytic view essentially recalculates all of the parameters again (as the available choices may have changed).
However it wasn't recalculating the aggregator parameter. This meant that when you clicked on the panel and it attempts to reload the options an out of bounds exception would be created as the parameter seemed to no longer exist.

I didn't confirm that it no longer exists, but recreating it fixes the issue....

Not sure what the actual true root cause is. I suspect that there is something up with its update logic, im going to keep looking for today but really it needs some in depth analysis.

**Comment by Nova-2119** [comment]
Currently I would bet that the issue is actually AnalyticViewTopComponent:127-131. In this bit of code createParameters() is called but if you look at the javadoc for it it says:
"This method will only be called once and the results will be cached for future use."
Which makes it seem like it shouldn't be getting called here and instead we should be updating the parameters a different way.
