### ISSUE TITLE
New Sphere Graph Button Null Pointer

### ISSUE THREAD

**Issue by aldebaran30701** [constellation-app/constellation#928]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

This issue does not occur when manually creating the sphere graph through experimental menu. 
You will have to click the new graph sphere network button on the welcome page.

It should load a new graph with a sphere rendered, but sometimes it just throws a null pointer and fails to render. it seems like the graph is generated already because all the element counts are present.

 
![render1](https://user-images.githubusercontent.com/58677759/104267942-a2774680-54e2-11eb-874c-af9c6bef4272.gif)

```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.LineBatcher.drawBatch(LineBatcher.java:325)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.display(GraphRenderable.java:472)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.lambda$display$3(GLRenderer.java:170)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GLRenderer.display(GLRenderer.java:169)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1428)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
Caused: com.jogamp.opengl.GLException: Caught NullPointerException: null on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1442)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:503)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:557)
	at java.desktop/sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at java.desktop/sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at java.desktop/sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5069)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Steps to Reproduce

1. Open fresh constellation program.
2. Click new graph (sphere network) button

**Expected behaviour:** generate a new sphere graph and render the contents

**Actual behaviour:** gets stuck generating the graph and does not render the contents.

**Reproduces how often:** 70%

### Additional Information

There is a possibility that this will not occur consistently. Unsure of the trigger, as you can load another graph and then click the button and it seems to work flawlessly.

**Comment by mimosa2** [comment]
I have tested this in latest master branch. The NullPointerException doesn't happen anymore.
