### ISSUE TITLE
Exception opening graph without Plugin Reporter

### ISSUE THREAD

**Issue by arcturus2** [constellation-app/constellation#949]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

If you close the plugin reporter, restart Constellation and try to open a graph I always get a `ConcurrentModificationException`.

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at au.gov.asd.tac.constellation.graph.node.plugins.FrameworkGraphManager.graphOpened(FrameworkGraphManager.java:102)
	at au.gov.asd.tac.constellation.graph.node.GraphNode.<init>(GraphNode.java:162)
	at au.gov.asd.tac.constellation.graph.node.GraphNode.<init>(GraphNode.java:135)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphTopComponent.<init>(VisualGraphTopComponent.java:451)
	at au.gov.asd.tac.constellation.graph.interaction.gui.VisualGraphOpener$GraphFileOpener.done(VisualGraphOpener.java:222)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Steps to Reproduce

1. Close the plugin reporter
2. Restart Constellation
3. Open a new analytic graph

**Expected behaviour:**
No errors thank you

**Actual behaviour:** 
ConcurrentModificationException

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by aldebaran30701** [comment]
Closely resembles the trace of #707

**Comment by antares1470** [comment]
> Closely resembles the trace of #707

Yep. I believe this tickets reflects the actual problem so we'll keep this one and close the other one

**Comment by Nova-2119** [comment]
@aldebaran30701 @arcturus2 I was unable to reproduce this on the current version of master, have either of you been able to?

**Comment by antares1470** [comment]
@Nova-2119 I manage to get the issue to replicate when the Plugin Reporter is closed and the DAV is open

**Comment by Nova-2119** [comment]
@antares1470 got it! Cheers.

**Comment by Nova-2119** [comment]
Hmm okay so it looks like the cause is that:
1) **FrameworkGraphManager.graphOpener** is called, this loops through _listeners_. While this is looping _listeners_ cannot be modified.
2) **FrameworkGraphManager.addGraphManagerListener** is called prior to **graphOpener** finishing. This may then add new listeners' to _listeners_.
3) As _listeners_ has been modified it throws a concurrent modification when it attmpts to get the next entry because the behaviour is undefined now that _listeners_ has been modified.

Next step is to see why this only occurs when the plugin reporter is open. What behaviour has changed?

**Comment by Nova-2119** [comment]
So in conditions where the error isn't thrown addGraphManagerListener is still called but only for the last listener in listeners. Therefore an error isn't thrown because its reached the end of the iteration. I wonder if this is accidental or if there is a deliberate ordering happening that doesn't happen in the case where we get the error, it certainly calls that method prior to the last listener in any case.

**Comment by Nova-2119** [comment]
I have went through every view and confirmed that the problem is specific the the quality control view. It also occurs when the Data Acces view is open but im confident this is just because of the quality control widget the view has. Essentially having the Quality Control View (or a widget) open causes **FrameworkGraphManager.addGraphManagerListener** to add a GraphReportManager listener whilst we are looping through the listeners, causing an error.

But when the pluginReport view is open this triggers **FrameworkGraphManager.addGraphManagerListener** to be called upon initially opening constellation. This means when you open a graph and the same method is called it doesn't modify listeners because a GraphReportManager listener is already in listeners. This eeffectively counteracts the issue above which is why it doesnt occur is the plugin reporter is open.

Next step is to try and stop the quality control view from exhibiting this behaviour as none of the other views do it. I will also add a comment to the method which casues the addition of the listener warning against it being used in the initialisation of views.

**Comment by arcturus2** [comment]
@Nova-2119 many many thanks for the detailed explanation and keeping us up to date with what is going on. Well done for nailing this one down to the Quality Control View.
