### ISSUE TITLE
Constellation Exception if Importing CSV file

### ISSUE THREAD

**Issue by serpens24** [constellation-app/constellation#968]
<!--

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Running the latest version of Constellation
	* Attached the ***Support Package*** via `Help` > `Support Package`
    * Checked the FAQs: https://github.com/constellation-app/constellation/wiki/FAQ
    * Checked that your issue isn't already filed: https://github.com/constellation-app/constellation/issues
    * Checked that there is not already a module that provides the described functionality: https://github.com/constellation-app/constellation/wiki/Catalogue-of-Repositories

### Description

Running latest github version of Constellation.  Trying to import a CSV file failed and returns an exception trace.
Note, while I beleive the CSV I used is valid, even if this was not the case, an exception should not be thrown to the user.

### Steps to Reproduce

1. Open a new instance of Constellation Ensure only Tutorial and Welcome pages present .... ie definitely no Delimited File Import window visible.
2. Select File->Import->From Delimited File...
3. Immediately select file to import (green cross) and press OK. **** timing is important ****
4. NOTE an exception.
5. Remove the import that failed and re-add it. (file import -> green cross, and press OK.
6. NOTE the import preview displays with no errors. 
7. Close the Import screen. 
8. Repeat steps 1->7, howeverthis time, pause (for about a minute) before step 3 and note the error doesnt occur.

**Expected behaviour:** 
No exceptions at steps 4 and 8.

**Actual behaviour:**
Exceptions at steps 4 and 8.

**Reproduces how often:**
100% depending on timing

### Additional Information

The exception thrown is:

---------------------------------------------------------------------------------------
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.plugins.importexport.delimited.RunPane.setSampleData(RunPane.java:443)
	at au.gov.asd.tac.constellation.plugins.importexport.delimited.ConfigurationPane.setSampleData(ConfigurationPane.java:169)
	at au.gov.asd.tac.constellation.plugins.importexport.delimited.ImportController.updateSampleData(ImportController.java:500)
	at au.gov.asd.tac.constellation.plugins.importexport.delimited.ImportController.setFiles(ImportController.java:185)
	at au.gov.asd.tac.constellation.plugins.importexport.delimited.SourcePane.lambda$new$2(SourcePane.java:193)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8879)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$4(EmbeddedScene.java:286)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$5(EmbeddedScene.java:279)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
---------------------------------------------------------------------------------------

Attached an example (zipped) csv to test with.

[Sacramentorealestatetransactions.zip](https://github.com/constellation-app/constellation/files/5963187/Sacramentorealestatetransactions.zip)

**Comment by serpens24** [comment]
A quick code inspection suggests the following:

The RunPane constructor in au.gov.asd.tac.constellation.plugins.importexport.delimited.RunPane.setSampleData(RunPane.java at lines 146-150 checks if rowFilter exists, if it does not, a new thread is created to accomodate it.

The exception being thrown at line 443 (in setSampleData method) is dependant on this class member (rowFilter) existing, which potentially may not if the user quickly chooses to import a file.

**Comment by serpens24** [comment]
@arcturus2 - it appears the issue is the result of the code below (lines 146-150 of RunPane.java) - to show this I replaced the new Thread creation with a single linecreating the rowFilter and the issue went away. So this would fix it, but wanted to understand if that would impact on the reason the thread was there - I note it was added in  commit https://github.com/constellation-app/constellation/pull/847/commits/b9e3696aae942f78f4fa265385f6cfce4e831732

My supicion is this was done to speed up loading, the trade off being we can get the issue listed here. 


        if (rowFilter == null) {
            new Thread(() -> {
                rowFilter = new RowFilter();
            }, ROW_FILTER_INITIALISER).start();
        }

**Comment by arcturus2** [comment]
OK @serpens24 thats good debugging. Yep I did add the new thread to improve performance and this is the only reason. I wonder if there is a way to have the best of both worlds. Would a check for `null` and wait be an option? How about `synchronizng` on a  `LOCK` object?

**Comment by GammaVel** [comment]
@serpens24 Improvements have recently been made in this area with v2.4 r2. Is this still happening for you?

**Comment by Auriga2** [comment]
We haven't fixed anything around the lines quoted here, but cannot recreate the exception either.
Looks like the last line in https://github.com/constellation-app/constellation/pull/1124/commits/9460eb87bfee8b610b45c332e813148c00413710 fixes the same issue, because it was added to fix the below exception in `setFilter`:
> java.lang.NullPointerException
> 	at au.gov.asd.tac.constellation.plugins.importexport.RunPane.setFilter(RunPane.java:490)
> 	at au.gov.asd.tac.constellation.plugins.importexport.RunPane.lambda$new$1(RunPane.java:182)

**Comment by antares1470** [comment]
I believe this is done as I tested removing some null checks for `rowFilter` (that wouldn't have been present when this issue was created) and was able to get the exception following the reproducer. Couldn't get it happen with the null checks in place
